CREATE VIEW [RDS].[vwTitleIIIELOct_FactTable_141] 
AS
	SELECT 	f.[FactK12StudentCountId]
			, f.[SchoolYear]
		  	, f.[K12Student_CurrentId]
		  	, f.[K12StudentStudentIdentifierState]
		  	, f.[BirthDate]
		  	, f.[FirstName]
		  	, f.[LastOrSurname]
		  	, f.[MiddleName]
		  	, f.[StateANSICode]
		  	, f.[StateAbbreviationCode]
		  	, f.[StateAbbreviationDescription]
		  	, f.[SeaOrganizationIdentifierSea]
		  	, f.[SeaOrganizationName]
		  	, f.[LeaIdentifierSea]
		  	, f.[LeaOrganizationName]
		  	, f.[SchoolIdentifierSea]
		  	, f.[DimK12SchoolId]
		  	, f.[NameOfInstitution]
		  	, f.[SchoolOperationalStatus]
		  	, f.[SchoolTypeCode]
			-- 14.1: FS141 dims GradeLevel / ISO6392LanguageCode / IdeaIndicator / Race
			, f.[GradeLevelEdFactsCode]
			, f.[Iso6392LanguageCodeEdFactsCode]
			, f.[IdeaIndicatorEdFactsCode]
			, f.[RaceEdFactsCode]
	FROM [debug].[vwTitleIIIELOct_FactTable] f
	WHERE SchoolOperationalStatus IN ('Open','New')
