CREATE VIEW [RDS].[vwDropout_FactTable_032] 
AS
	SELECT 	f.[FactK12StudentCountId]
			, f.[SchoolYear]
		  	, f.[K12Student_CurrentId]
		  	, f.[K12StudentStudentIdentifierState]
		  	, f.[BirthDate]
		  	, f.[FirstName]
		  	, f.[LastOrSurname]
		  	, f.[MiddleName]
		  	, f.[StateANSICode]
		  	, f.[StateAbbreviationCode]
		  	, f.[StateAbbreviationDescription]
		  	, f.[SeaOrganizationIdentifierSea]
		  	, f.[SeaOrganizationName]
		  	, f.[LeaIdentifierSea]
		  	, f.[LeaOrganizationName]
		  	, f.[SchoolIdentifierSea]
		  	, f.[DimK12SchoolId]
		  	, f.[NameOfInstitution]
		  	, f.[SchoolOperationalStatus]
		  	, f.[SchoolTypeCode]
			-- 14.1: FS032 breaks out by 8 dimensions; surface each dimension's EdFacts code for
			-- RDS.Insert_CountsIntoReportTable's permitted-value join (was Msg 207).
			, f.[EconomicDisadvantageStatusEdFactsCode]
			, f.[EnglishLearnerStatusEdFactsCode]
			, f.[GradeLevelEdFactsCode]
			, f.[HomelessnessStatusEdFactsCode]
			, f.[IdeaIndicatorEdFactsCode]
			, f.[MigrantStatusEdFactsCode]
			, f.[RaceEdFactsCode]
			, f.[SexEdFactsCode]
	FROM [debug].[vwDropout_FactTable] f
	WHERE SchoolOperationalStatus IN ('Open','New')
