IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetRefStateAnsiCode') BEGIN
	DROP FUNCTION [App].[GetRefStateAnsiCode]
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'GetRefStateAnsiCode') BEGIN
	DROP FUNCTION [Staging].[GetRefStateAnsiCode]
END