IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetProgramTypeId') BEGIN
	DROP FUNCTION [App].[GetProgramTypeId]
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'GetProgramTypeId') BEGIN
	DROP FUNCTION [Staging].[GetProgramTypeId]
END