IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'Migrate_Data_Validation_Logging') BEGIN
	DROP PROCEDURE [App].[Migrate_Data_Validation_Logging]
END