INSERT INTO App.GenerateReports (
	FactTableId
	,GenerateReportControlTypeId
	,GenerateReportTypeId
	,IsActive
	,ReportCode
	,ReportName
	,ReportShortName
	,ShowCategorySetControl
	,ShowData
	,ShowFilterControl
	,ShowGraph
	,ShowSubFilterControl
	,IsLocked
	,UseLegacyReportMigration
)
VALUES(
	1
	,2
	,3
	,1
	,'c210'
	,'C210: Title III English Learner Five Years'
	,'C210'
	,1
	,1
	,0
	,0
	,0
	,0
	,1
)

INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2021', N'CSA', N'Category Set A', N'21184', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSNO', N'Not proficient within five years', N'9502')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2021', N'CSA', N'Category Set A', N'21184', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSYES', N'Proficient within five years', N'9503')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2021', N'CSA', N'Category Set A', N'21184', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'MISSING', N'Missing', N'-1')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2021', N'EUT', N'Education Unit Total', N'21209', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'NOCATS', N'No Categories', N'-100', N'NOCODES', N'No Category Codes', N'-100')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2021', N'EUT', N'Education Unit Total', N'21185', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'NOCATS', N'No Categories', N'-100', N'NOCODES', N'No Category Codes', N'-100')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2021', N'CSA', N'Category Set A', N'21210', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSNO', N'Not proficient within five years', N'9502')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2021', N'CSA', N'Category Set A', N'21210', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSYES', N'Proficient within five years', N'9503')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2021', N'CSA', N'Category Set A', N'21210', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'MISSING', N'Missing', N'-1')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2022', N'CSA', N'Category Set A', N'21630', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSNO', N'Not proficient within five years', N'9502')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2022', N'CSA', N'Category Set A', N'21630', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSYES', N'Proficient within five years', N'9503')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2022', N'CSA', N'Category Set A', N'21630', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'MISSING', N'Missing', N'-1')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'SEA TITLE III ENGLISH LEARNER 5 YRS', N'1', N'2022', N'EUT', N'Education Unit Total', N'21632', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'NOCATS', N'No Categories', N'-100', N'NOCODES', N'No Category Codes', N'-100')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2022', N'EUT', N'Education Unit Total', N'21631', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'NOCATS', N'No Categories', N'-100', N'NOCODES', N'No Category Codes', N'-100')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2022', N'CSA', N'Category Set A', N'21633', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSNO', N'Not proficient within five years', N'9502')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2022', N'CSA', N'Category Set A', N'21633', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'PROF5YRSYES', N'Proficient within five years', N'9503')
INSERT INTO [App].[vwReportCode_CategoryOptions] ([ReportCode], [FileSubmissionDescription], [OrganizationLevelId], [SubmissionYear], [CategorySetCode], [CategorySetName], [EdFactsTableTypeGroupId], [EdFactsTableTypeId], [TableTypeAbbrv], [TableTypeName], [CategoryCode], [CategoryName], [EdFactsCategoryId], [CategoryOptionCode], [CategoryOptionName], [EdFactsCategoryCodeId]) VALUES (N'c210', N'LEA TITLE III ENGLISH LEARNER 5 YRS', N'2', N'2022', N'CSA', N'Category Set A', N'21633', N'282', N'TTL3EL5YRS', N'Title III English learners five years table', N'ELPROF5YRSTS', N'English Learners Proficiency Within Five Years Status', N'614', N'MISSING', N'Missing', N'-1')

INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'FileRecordNumber', N'File Record Number', N'', N'Number', N'10', N'1', N'1', N'1', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'FIPSStateCode', N'State Code', N'FIPSSTATECODE', N'String', N'12', N'1', N'2', N'11', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'StateAgencyNumber', N'State Agency Number', N'STATEAGENCYNUMBER', N'String', N'14', N'1', N'3', N'13', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'14', N'Filler1', N'Filler', N'', N'String', N'28', N'1', N'4', N'15', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'Filler2', N'Filler', N'', N'String', N'48', N'1', N'5', N'29', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'TableTypeAbbrv', N'Table Type Abbreviation', N'TYPEABBRV', N'String', N'68', N'1', N'6', N'49', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'15', N'ELProf5YrStatusID', N'English Learners Proficiency Within Five Years Status', N'CATEGORY', N'String', N'83', N'0', N'7', N'69', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'TotalIndicator', N'Total Indicator', N'TOTALINDICATOR', N'String', N'84', N'1', N'8', N'84', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'200', N'Explanation', N'Explanation', N'EXPLANATION', N'String', N'284', N'0', N'9', N'85', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'Amount', N'Student Count', N'AMOUNT', N'Decimal2', N'294', N'1', N'10', N'285', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'CarriageReturn/LineFeed', N'Carriage Return / Line Feed (CRLF)', N'', N'Control Character', N'295', N'1', N'11', N'295', N'2021', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'FileRecordNumber', N'File Record Number', N'', N'Number', N'10', N'1', N'1', N'1', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'FIPSStateCode', N'State Code', N'FIPSSTATECODE', N'String', N'12', N'1', N'2', N'11', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'StateAgencyNumber', N'State Agency Number', N'STATEAGENCYNUMBER', N'String', N'14', N'1', N'3', N'13', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'14', N'StateLEAIDNumber', N'LEA Identifier (State)', N'STATELEAIDNUMBER', N'String', N'28', N'1', N'4', N'15', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'Filler1', N'Filler', N'', N'String', N'48', N'1', N'5', N'29', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'TableTypeAbbrv', N'Table Type Abbreviation', N'TYPEABBRV', N'String', N'68', N'1', N'6', N'49', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'15', N'ELProf5YrStatusID', N'English Learners Proficiency Within Five Years Status', N'CATEGORY', N'String', N'83', N'0', N'7', N'69', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'TotalIndicator', N'Total Indicator', N'TOTALINDICATOR', N'String', N'84', N'1', N'8', N'84', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'200', N'Explanation', N'Explanation', N'EXPLANATION', N'String', N'284', N'0', N'9', N'85', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'Amount', N'Student Count', N'AMOUNT', N'Decimal2', N'294', N'1', N'10', N'285', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'CarriageReturn/LineFeed', N'Carriage Return / Line Feed (CRLF)', N'', N'Control Character', N'295', N'1', N'11', N'295', N'2021', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'FileRecordNumber', N'File Record Number', N'', N'Number', N'10', N'1', N'1', N'1', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'FIPSStateCode', N'State Code', N'FIPSSTATECODE', N'String', N'12', N'1', N'2', N'11', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'StateAgencyNumber', N'State Agency Number', N'STATEAGENCYNUMBER', N'String', N'14', N'1', N'3', N'13', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'14', N'Filler1', N'Filler', N'', N'String', N'28', N'1', N'4', N'15', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'Filler2', N'Filler', N'', N'String', N'48', N'1', N'5', N'29', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'TableTypeAbbrv', N'Table Type Abbreviation', N'TYPEABBRV', N'String', N'68', N'1', N'6', N'49', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'15', N'ELProf5YrStatusID', N'English Learners Proficiency Within Five Years Status', N'CATEGORY', N'String', N'83', N'0', N'7', N'69', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'TotalIndicator', N'Total Indicator', N'TOTALINDICATOR', N'String', N'84', N'1', N'8', N'84', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'200', N'Explanation', N'Explanation', N'EXPLANATION', N'String', N'284', N'0', N'9', N'85', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'Amount', N'Student Count', N'AMOUNT', N'Decimal2', N'294', N'1', N'10', N'285', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'CarriageReturn/LineFeed', N'Carriage Return / Line Feed (CRLF)', N'', N'Control Character', N'295', N'1', N'11', N'295', N'2022', N'1', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'FileRecordNumber', N'File Record Number', N'', N'Number', N'10', N'1', N'1', N'1', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'FIPSStateCode', N'State Code', N'FIPSSTATECODE', N'String', N'12', N'1', N'2', N'11', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'2', N'StateAgencyNumber', N'State Agency Number', N'STATEAGENCYNUMBER', N'String', N'14', N'1', N'3', N'13', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'14', N'StateLEAIDNumber', N'LEA Identifier (State)', N'STATELEAIDNUMBER', N'String', N'28', N'1', N'4', N'15', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'Filler1', N'Filler', N'', N'String', N'48', N'1', N'5', N'29', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'20', N'TableTypeAbbrv', N'Table Type Abbreviation', N'TYPEABBRV', N'String', N'68', N'1', N'6', N'49', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'15', N'ELProf5YrStatusID', N'English Learners Proficiency Within Five Years Status', N'CATEGORY', N'String', N'83', N'0', N'7', N'69', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'TotalIndicator', N'Total Indicator', N'TOTALINDICATOR', N'String', N'84', N'1', N'8', N'84', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'200', N'Explanation', N'Explanation', N'EXPLANATION', N'String', N'284', N'0', N'9', N'85', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'10', N'Amount', N'Student Count', N'AMOUNT', N'Decimal2', N'294', N'1', N'10', N'285', N'2022', N'2', N'c210')
INSERT INTO [App].[vwReportCode_FileColumns] ([ColumnLength], [ColumnName], [DisplayName], [XMLElementName], [DataType], [EndPosition], [IsOptional], [SequenceNumber], [StartPosition], [SubmissionYear], [OrganizationLevelId], [ReportCode]) VALUES (N'1', N'CarriageReturn/LineFeed', N'Carriage Return / Line Feed (CRLF)', N'', N'Control Character', N'295', N'1', N'11', N'295', N'2022', N'2', N'c210')
