version: '3'
services:
  generate:
    image: svuyuru/generate.web:V12.1
    ports:
            - 8080:80
    build: 
        context: .

    networks:
            - web-app
networks:
  web-app:
    name: generate_network
    external: true