
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS where TABLE_SCHEMA = 'RDS' AND TABLE_NAME = 'DimFirearms' AND COLUMN_NAME = 'FirearmTypeCode')
	BEGIN
	    UPDATE RDS.DimFirearms SET FirearmTypeCode = 'RIFLESSHOTGUNS' WHERE FirearmTypeCode = 'RIFLESHOTGUN'
	END
