	IF COL_LENGTH('RDS.ReportEDFactsK12StudentAssessments', 'TITLEIPROGRAMTYPE') IS NOT NULL
	BEGIN
		EXEC sp_rename 'RDS.ReportEDFactsK12StudentAssessments.TITLEIPROGRAMTYPE', 'TITLEIINDICATOR', 'COLUMN';
	END