CREATE TABLE [Staging].[K12Enrollment] (
    [Id]                                   INT            IDENTITY (1, 1) NOT NULL,
    [Student_Identifier_State]             VARCHAR (100)  NULL,
    [LEA_Identifier_State]                 VARCHAR (100)  NULL,
    [School_Identifier_State]              VARCHAR (100)  NULL,
    [FirstName]                            VARCHAR (100)  NULL,
    [LastName]                             VARCHAR (100)  NULL,
    [MiddleName]                           VARCHAR (100)  NULL,
    [Birthdate]                            DATE           NULL,
    [Sex]                                  VARCHAR (30)   NULL,
    [HispanicLatinoEthnicity]              BIT            NULL,
    [EnrollmentEntryDate]                  DATE           NULL,
    [EnrollmentExitDate]                   DATE           NULL,
    [ExitOrWithdrawalType]                 VARCHAR (100)  NULL,
    [GradeLevel]                           VARCHAR (100)  NULL,
    [CohortYear]                           NCHAR (4)      NULL,
    [CohortGraduationYear]                 NCHAR (4)      NULL,
    [CohortDescription]                    NCHAR (1024)   NULL,
    [HighSchoolDiplomaType]                VARCHAR (100)  NULL,
    [PersonId]                             INT            NULL,
    [OrganizationID_LEA]                   INT            NULL,
    [OrganizationPersonRoleId_LEA]         INT            NULL,
    [OrganizationID_School]                INT            NULL,
    [OrganizationPersonRoleId_School]      INT            NULL,
    [OrganizationPersonRoleRelationshipId] INT            NULL,
    [RunDateTime]                          DATETIME       NULL,
    [SchoolYear]                           VARCHAR (100)  NULL,
    [NumberOfSchoolDays]                   DECIMAL (9, 2) NULL,
    [NumberOfDaysAbsent]                   DECIMAL (9, 2) NULL,
    [AttendanceRate]                       DECIMAL (5, 4) NULL,
    [PostSecondaryEnrollment]              BIT            NULL,
    [DiplomaOrCredentialAwardDate]         DATE           NULL,
    [FoodServiceEligibility]               VARCHAR (100)  NULL,
    CONSTRAINT [PK_K12Enrollment] PRIMARY KEY CLUSTERED ([Id] ASC)
);


