
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Utilities' AND ROUTINE_NAME = 'CompareSubmissionFiles') 
BEGIN
	DROP PROCEDURE [Utilities].[CompareSubmissionFiles]
END








