IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetPersonIdentifierSystemId') BEGIN
	DROP FUNCTION [App].[GetPersonIdentifierSystemId]
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'GetPersonIdentifierSystemId') BEGIN
	DROP FUNCTION [Staging].[GetPersonIdentifierSystemId]
END