IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'App' AND ROUTINE_NAME = 'ESS_MetadataAudit_Year_ReportCode') BEGIN
	DROP PROCEDURE [App].[ESS_MetadataAudit_Year_ReportCode]
END
