IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'Wrapper_Migrate_Homeless_to_RDS') 
BEGIN
	DROP PROCEDURE [App].[Wrapper_Migrate_Homeless_to_RDS]
END



