IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'debug' AND ROUTINE_NAME = 'Cleanup_Debug_Tables') 
BEGIN
	DROP PROCEDURE [debug].[Cleanup_Debug_Tables]
END


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'app' AND ROUTINE_NAME = 'Cleanup_Grades_Offered') 
BEGIN
	DROP PROCEDURE [app].[Cleanup_Grades_Offered]
END


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'staging' AND ROUTINE_NAME = 'DisableIndexes') 
BEGIN
	DROP PROCEDURE [staging].[DisableIndexes]
END


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'staging' AND ROUTINE_NAME = 'RebuildIndexes') 
BEGIN
	DROP PROCEDURE [staging].[RebuildIndexes]
END
