using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using generate.core.Models.RDS;

namespace generate.core.Helpers.ReferenceData
{
    public class DimComprehensiveAndTargetedSupportHelper
    {
        public static List<DimComprehensiveAndTargetedSupport> GetData()
        {


            var data = new List<DimComprehensiveAndTargetedSupport>();

            /*
            select 'data.Add(new DimComprehensiveAndTargetedSupport() { 
            DimComprehensiveAndTargetedSupportId = ' + convert(varchar(20), DimComprehensiveAndTargetedSupportId) + ',
            ComprehensiveAndTargetedSupportEdFactsCode = "' + ComprehensiveAndTargetedSupportEdFactsCode + '",
            TargetedSupportEdFactsCode = "' + TargetedSupportEdFactsCode + '",
            ComprehensiveSupportEdFactsCode = "' + ComprehensiveSupportEdFactsCode + '",
			ComprehensiveSupportImprovementEdFactsCode = "' + ComprehensiveSupportImprovementEdFactsCode + '",
			TargetedSupportImprovementEdFactsCode = "' + TargetedSupportImprovementEdFactsCode + '",
			AdditionalTargetedSupportandImprovementEdFactsCode = "' + AdditionalTargetedSupportandImprovementEdFactsCode + '"			
            });'
            from rds.DimComprehensiveAndTargetedSupports
            */


            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = -1, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 1, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 2, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 3, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 4, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 5, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 6, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 7, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 8, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 9, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 10, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 11, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 12, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 13, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 14, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 15, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 16, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 17, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 18, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 19, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 20, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 21, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 22, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 23, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 24, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 25, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 26, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 27, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 28, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 29, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 30, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 31, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 32, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 33, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 34, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 35, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 36, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 37, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 38, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 39, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 40, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 41, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 42, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 43, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 44, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 45, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 46, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 47, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 48, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 49, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 50, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 51, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 52, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 53, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 54, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 55, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 56, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 57, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 58, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 59, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 60, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 61, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 62, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 63, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 64, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 65, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 66, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 67, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 68, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 69, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 70, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 71, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 72, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 73, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 74, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 75, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 76, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 77, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 78, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 79, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 80, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 81, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 82, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 83, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 84, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 85, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 86, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 87, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 88, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 89, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 90, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 91, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 92, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 93, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 94, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 95, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 96, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 97, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 98, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 99, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 100, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 101, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 102, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 103, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 104, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 105, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 106, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 107, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 108, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 109, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 110, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 111, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 112, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 113, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 114, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 115, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 116, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 117, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 118, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 119, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 120, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 121, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 122, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 123, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 124, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 125, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 126, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 127, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 128, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 129, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 130, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 131, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 132, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 133, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 134, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 135, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 136, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 137, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 138, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 139, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 140, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 141, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 142, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 143, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 144, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 145, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 146, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 147, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 148, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 149, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 150, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 151, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 152, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 153, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 154, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 155, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 156, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 157, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 158, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 159, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 160, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 161, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 162, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 163, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 164, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 165, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 166, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 167, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 168, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 169, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 170, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 171, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 172, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 173, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 174, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 175, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 176, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 177, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 178, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 179, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 180, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 181, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 182, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 183, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWPERF", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 184, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 185, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 186, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSILOWGR", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 187, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 188, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 189, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "CSIOTHER", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 190, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIUNDER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 191, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "TSIOTHER", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "MISSING" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 192, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 193, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 194, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 195, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 196, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 197, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 198, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 199, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 200, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 201, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 202, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 203, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 204, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 205, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 206, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 207, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "ADDLTSI" });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 208, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 209, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 210, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 211, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 212, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 213, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 214, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 215, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "CSIEXIT", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 216, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 217, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 218, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 219, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "NOTCSI", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 220, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 221, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "TSIEXIT", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 222, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "NOTTSI", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });
            data.Add(new DimComprehensiveAndTargetedSupport() { DimComprehensiveAndTargetedSupportId = 223, ComprehensiveAndTargetedSupportEdFactsCode = "MISSING", TargetedSupportEdFactsCode = "MISSING", ComprehensiveSupportEdFactsCode = "MISSING", ComprehensiveSupportImprovementEdFactsCode = "MISSING", TargetedSupportImprovementEdFactsCode = "MISSING", AdditionalTargetedSupportandImprovementEdFactsCode = "NOTADDLTSI " });

            return data;

        }
    }
}
 