using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using generate.core.Models.RDS;

namespace generate.core.Helpers.ReferenceData
{
    public class DimLanguageHelper
    {
        public static List<DimLanguage> GetData()
        {


            var data = new List<DimLanguage>();

            /*
            select 'data.Add(new DimLanguage() { 
            DimLanguageId = ' + convert(varchar(20), DimLanguageId) + ',
            LanguageEdFactsCode = "' + LanguageEdFactsCode + '",
            LanguageDescription = "' + LanguageDescription + '"
            });'
            from rds.DimLanguages
            */

            //data.Add(new DimLanguage() { DimLanguageId = -1, LanguageEdFactsCode = "MISSING", LanguageDescription = "Missing" });
            //data.Add(new DimLanguage() { DimLanguageId = 1, LanguageEdFactsCode = "aar", LanguageDescription = "Afar" });
            //data.Add(new DimLanguage() { DimLanguageId = 2, LanguageEdFactsCode = "abk", LanguageDescription = "Abkhazian" });
            //data.Add(new DimLanguage() { DimLanguageId = 3, LanguageEdFactsCode = "ace", LanguageDescription = "Achinese" });
            //data.Add(new DimLanguage() { DimLanguageId = 4, LanguageEdFactsCode = "ach", LanguageDescription = "Acoli" });
            //data.Add(new DimLanguage() { DimLanguageId = 5, LanguageEdFactsCode = "ada", LanguageDescription = "Adangme" });
            //data.Add(new DimLanguage() { DimLanguageId = 6, LanguageEdFactsCode = "ady", LanguageDescription = "Adyghe; Adygei" });
            //data.Add(new DimLanguage() { DimLanguageId = 7, LanguageEdFactsCode = "afa", LanguageDescription = "Afro-Asiatic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 8, LanguageEdFactsCode = "afh", LanguageDescription = "Afrihili" });
            //data.Add(new DimLanguage() { DimLanguageId = 9, LanguageEdFactsCode = "afr", LanguageDescription = "Afrikaans" });
            //data.Add(new DimLanguage() { DimLanguageId = 10, LanguageEdFactsCode = "ain", LanguageDescription = "Ainu" });
            //data.Add(new DimLanguage() { DimLanguageId = 11, LanguageEdFactsCode = "aka", LanguageDescription = "Akan" });
            //data.Add(new DimLanguage() { DimLanguageId = 12, LanguageEdFactsCode = "akk", LanguageDescription = "Akkadian" });
            //data.Add(new DimLanguage() { DimLanguageId = 13, LanguageEdFactsCode = "alb", LanguageDescription = "Albanian" });
            //data.Add(new DimLanguage() { DimLanguageId = 14, LanguageEdFactsCode = "ale", LanguageDescription = "Aleut" });
            //data.Add(new DimLanguage() { DimLanguageId = 15, LanguageEdFactsCode = "alg", LanguageDescription = "Algonquian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 16, LanguageEdFactsCode = "alt", LanguageDescription = "Southern Altai" });
            //data.Add(new DimLanguage() { DimLanguageId = 17, LanguageEdFactsCode = "amh", LanguageDescription = "Amharic" });
            //data.Add(new DimLanguage() { DimLanguageId = 18, LanguageEdFactsCode = "ang", LanguageDescription = "English, Old (ca.450-1100)" });
            //data.Add(new DimLanguage() { DimLanguageId = 19, LanguageEdFactsCode = "anp", LanguageDescription = "Angika" });
            //data.Add(new DimLanguage() { DimLanguageId = 20, LanguageEdFactsCode = "apa", LanguageDescription = "Apache languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 21, LanguageEdFactsCode = "ara", LanguageDescription = "Arabic" });
            //data.Add(new DimLanguage() { DimLanguageId = 22, LanguageEdFactsCode = "arc", LanguageDescription = "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)" });
            //data.Add(new DimLanguage() { DimLanguageId = 23, LanguageEdFactsCode = "arg", LanguageDescription = "Aragonese" });
            //data.Add(new DimLanguage() { DimLanguageId = 24, LanguageEdFactsCode = "arm", LanguageDescription = "Armenian" });
            //data.Add(new DimLanguage() { DimLanguageId = 25, LanguageEdFactsCode = "arn", LanguageDescription = "Mapudungun; Mapuche" });
            //data.Add(new DimLanguage() { DimLanguageId = 26, LanguageEdFactsCode = "arp", LanguageDescription = "Arapaho" });
            //data.Add(new DimLanguage() { DimLanguageId = 27, LanguageEdFactsCode = "art", LanguageDescription = "Artificial languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 28, LanguageEdFactsCode = "arw", LanguageDescription = "Arawak" });
            //data.Add(new DimLanguage() { DimLanguageId = 29, LanguageEdFactsCode = "asm", LanguageDescription = "Assamese" });
            //data.Add(new DimLanguage() { DimLanguageId = 30, LanguageEdFactsCode = "ast", LanguageDescription = "Asturian; Bable; Leonese; Asturleonese" });
            //data.Add(new DimLanguage() { DimLanguageId = 31, LanguageEdFactsCode = "ath", LanguageDescription = "Athapascan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 32, LanguageEdFactsCode = "aus", LanguageDescription = "Australian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 33, LanguageEdFactsCode = "ava", LanguageDescription = "Avaric" });
            //data.Add(new DimLanguage() { DimLanguageId = 34, LanguageEdFactsCode = "ave", LanguageDescription = "Avestan" });
            //data.Add(new DimLanguage() { DimLanguageId = 35, LanguageEdFactsCode = "awa", LanguageDescription = "Awadhi" });
            //data.Add(new DimLanguage() { DimLanguageId = 36, LanguageEdFactsCode = "aym", LanguageDescription = "Aymara" });
            //data.Add(new DimLanguage() { DimLanguageId = 37, LanguageEdFactsCode = "aze", LanguageDescription = "Azerbaijani" });
            //data.Add(new DimLanguage() { DimLanguageId = 38, LanguageEdFactsCode = "bad", LanguageDescription = "Banda languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 39, LanguageEdFactsCode = "bai", LanguageDescription = "Bamileke languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 40, LanguageEdFactsCode = "bak", LanguageDescription = "Bashkir" });
            //data.Add(new DimLanguage() { DimLanguageId = 41, LanguageEdFactsCode = "bal", LanguageDescription = "Baluchi" });
            //data.Add(new DimLanguage() { DimLanguageId = 42, LanguageEdFactsCode = "bam", LanguageDescription = "Bambara" });
            //data.Add(new DimLanguage() { DimLanguageId = 43, LanguageEdFactsCode = "ban", LanguageDescription = "Balinese" });
            //data.Add(new DimLanguage() { DimLanguageId = 44, LanguageEdFactsCode = "baq", LanguageDescription = "Basque" });
            //data.Add(new DimLanguage() { DimLanguageId = 45, LanguageEdFactsCode = "bas", LanguageDescription = "Basa" });
            //data.Add(new DimLanguage() { DimLanguageId = 46, LanguageEdFactsCode = "bat", LanguageDescription = "Baltic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 47, LanguageEdFactsCode = "bej", LanguageDescription = "Beja; Bedawiyet" });
            //data.Add(new DimLanguage() { DimLanguageId = 48, LanguageEdFactsCode = "bel", LanguageDescription = "Belarusian" });
            //data.Add(new DimLanguage() { DimLanguageId = 49, LanguageEdFactsCode = "bem", LanguageDescription = "Bemba" });
            //data.Add(new DimLanguage() { DimLanguageId = 50, LanguageEdFactsCode = "ben", LanguageDescription = "Bengali" });
            //data.Add(new DimLanguage() { DimLanguageId = 51, LanguageEdFactsCode = "ber", LanguageDescription = "Berber languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 52, LanguageEdFactsCode = "bho", LanguageDescription = "Bhojpuri" });
            //data.Add(new DimLanguage() { DimLanguageId = 53, LanguageEdFactsCode = "bih", LanguageDescription = "Bihari languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 54, LanguageEdFactsCode = "bik", LanguageDescription = "Bikol" });
            //data.Add(new DimLanguage() { DimLanguageId = 55, LanguageEdFactsCode = "bin", LanguageDescription = "Bini; Edo" });
            //data.Add(new DimLanguage() { DimLanguageId = 56, LanguageEdFactsCode = "bis", LanguageDescription = "Bislama" });
            //data.Add(new DimLanguage() { DimLanguageId = 57, LanguageEdFactsCode = "bla", LanguageDescription = "Siksika" });
            //data.Add(new DimLanguage() { DimLanguageId = 58, LanguageEdFactsCode = "bnt", LanguageDescription = "Bantu languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 59, LanguageEdFactsCode = "bos", LanguageDescription = "Bosnian" });
            //data.Add(new DimLanguage() { DimLanguageId = 60, LanguageEdFactsCode = "bra", LanguageDescription = "Braj" });
            //data.Add(new DimLanguage() { DimLanguageId = 61, LanguageEdFactsCode = "bre", LanguageDescription = "Breton" });
            //data.Add(new DimLanguage() { DimLanguageId = 62, LanguageEdFactsCode = "btk", LanguageDescription = "Batak languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 63, LanguageEdFactsCode = "bua", LanguageDescription = "Buriat" });
            //data.Add(new DimLanguage() { DimLanguageId = 64, LanguageEdFactsCode = "bug", LanguageDescription = "Buginese" });
            //data.Add(new DimLanguage() { DimLanguageId = 65, LanguageEdFactsCode = "bul", LanguageDescription = "Bulgarian" });
            //data.Add(new DimLanguage() { DimLanguageId = 66, LanguageEdFactsCode = "bur", LanguageDescription = "Burmese" });
            //data.Add(new DimLanguage() { DimLanguageId = 67, LanguageEdFactsCode = "byn", LanguageDescription = "Blin; Bilin" });
            //data.Add(new DimLanguage() { DimLanguageId = 68, LanguageEdFactsCode = "cad", LanguageDescription = "Caddo" });
            //data.Add(new DimLanguage() { DimLanguageId = 69, LanguageEdFactsCode = "cai", LanguageDescription = "Central American Indian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 70, LanguageEdFactsCode = "car", LanguageDescription = "Galibi Carib" });
            //data.Add(new DimLanguage() { DimLanguageId = 71, LanguageEdFactsCode = "cat", LanguageDescription = "Catalan; Valencian" });
            //data.Add(new DimLanguage() { DimLanguageId = 72, LanguageEdFactsCode = "cau", LanguageDescription = "Caucasian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 73, LanguageEdFactsCode = "ceb", LanguageDescription = "Cebuano" });
            //data.Add(new DimLanguage() { DimLanguageId = 74, LanguageEdFactsCode = "cel", LanguageDescription = "Celtic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 75, LanguageEdFactsCode = "cha", LanguageDescription = "Chamorro" });
            //data.Add(new DimLanguage() { DimLanguageId = 76, LanguageEdFactsCode = "chb", LanguageDescription = "Chibcha" });
            //data.Add(new DimLanguage() { DimLanguageId = 77, LanguageEdFactsCode = "che", LanguageDescription = "Chechen" });
            //data.Add(new DimLanguage() { DimLanguageId = 78, LanguageEdFactsCode = "chg", LanguageDescription = "Chagatai" });
            //data.Add(new DimLanguage() { DimLanguageId = 79, LanguageEdFactsCode = "chi", LanguageDescription = "Chinese" });
            //data.Add(new DimLanguage() { DimLanguageId = 80, LanguageEdFactsCode = "chk", LanguageDescription = "Chuukese" });
            //data.Add(new DimLanguage() { DimLanguageId = 81, LanguageEdFactsCode = "chm", LanguageDescription = "Mari" });
            //data.Add(new DimLanguage() { DimLanguageId = 82, LanguageEdFactsCode = "chn", LanguageDescription = "Chinook jargon" });
            //data.Add(new DimLanguage() { DimLanguageId = 83, LanguageEdFactsCode = "cho", LanguageDescription = "Choctaw" });
            //data.Add(new DimLanguage() { DimLanguageId = 84, LanguageEdFactsCode = "chp", LanguageDescription = "Chipewyan; Dene Suline" });
            //data.Add(new DimLanguage() { DimLanguageId = 85, LanguageEdFactsCode = "chr", LanguageDescription = "Cherokee" });
            //data.Add(new DimLanguage() { DimLanguageId = 86, LanguageEdFactsCode = "chu", LanguageDescription = "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" });
            //data.Add(new DimLanguage() { DimLanguageId = 87, LanguageEdFactsCode = "chv", LanguageDescription = "Chuvash" });
            //data.Add(new DimLanguage() { DimLanguageId = 88, LanguageEdFactsCode = "chy", LanguageDescription = "Cheyenne" });
            //data.Add(new DimLanguage() { DimLanguageId = 89, LanguageEdFactsCode = "cmc", LanguageDescription = "Chamic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 90, LanguageEdFactsCode = "cop", LanguageDescription = "Coptic" });
            //data.Add(new DimLanguage() { DimLanguageId = 91, LanguageEdFactsCode = "cor", LanguageDescription = "Cornish" });
            //data.Add(new DimLanguage() { DimLanguageId = 92, LanguageEdFactsCode = "cos", LanguageDescription = "Corsican" });
            //data.Add(new DimLanguage() { DimLanguageId = 93, LanguageEdFactsCode = "cpe", LanguageDescription = "Creoles and pidgins, English based" });
            //data.Add(new DimLanguage() { DimLanguageId = 94, LanguageEdFactsCode = "cpf", LanguageDescription = "Creoles and pidgins, French-based" });
            //data.Add(new DimLanguage() { DimLanguageId = 95, LanguageEdFactsCode = "cpp", LanguageDescription = "Creoles and pidgins, Portuguese-based" });
            //data.Add(new DimLanguage() { DimLanguageId = 96, LanguageEdFactsCode = "cre", LanguageDescription = "Cree" });
            //data.Add(new DimLanguage() { DimLanguageId = 97, LanguageEdFactsCode = "crh", LanguageDescription = "Crimean Tatar; Crimean Turkish" });
            //data.Add(new DimLanguage() { DimLanguageId = 98, LanguageEdFactsCode = "crp", LanguageDescription = "Creoles and pidgins " });
            //data.Add(new DimLanguage() { DimLanguageId = 99, LanguageEdFactsCode = "csb", LanguageDescription = "Kashubian" });
            //data.Add(new DimLanguage() { DimLanguageId = 100, LanguageEdFactsCode = "cus", LanguageDescription = "Cushitic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 101, LanguageEdFactsCode = "cze", LanguageDescription = "Czech" });
            //data.Add(new DimLanguage() { DimLanguageId = 102, LanguageEdFactsCode = "dak", LanguageDescription = "Dakota" });
            //data.Add(new DimLanguage() { DimLanguageId = 103, LanguageEdFactsCode = "dan", LanguageDescription = "Danish" });
            //data.Add(new DimLanguage() { DimLanguageId = 104, LanguageEdFactsCode = "dar", LanguageDescription = "Dargwa" });
            //data.Add(new DimLanguage() { DimLanguageId = 105, LanguageEdFactsCode = "day", LanguageDescription = "Land Dayak languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 106, LanguageEdFactsCode = "del", LanguageDescription = "Delaware" });
            //data.Add(new DimLanguage() { DimLanguageId = 107, LanguageEdFactsCode = "den", LanguageDescription = "Slave (Athapascan)" });
            //data.Add(new DimLanguage() { DimLanguageId = 108, LanguageEdFactsCode = "dgr", LanguageDescription = "Dogrib" });
            //data.Add(new DimLanguage() { DimLanguageId = 109, LanguageEdFactsCode = "din", LanguageDescription = "Dinka" });
            //data.Add(new DimLanguage() { DimLanguageId = 110, LanguageEdFactsCode = "div", LanguageDescription = "Divehi; Dhivehi; Maldivian" });
            //data.Add(new DimLanguage() { DimLanguageId = 111, LanguageEdFactsCode = "doi", LanguageDescription = "Dogri" });
            //data.Add(new DimLanguage() { DimLanguageId = 112, LanguageEdFactsCode = "dra", LanguageDescription = "Dravidian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 113, LanguageEdFactsCode = "dsb", LanguageDescription = "Lower Sorbian" });
            //data.Add(new DimLanguage() { DimLanguageId = 114, LanguageEdFactsCode = "dua", LanguageDescription = "Duala" });
            //data.Add(new DimLanguage() { DimLanguageId = 115, LanguageEdFactsCode = "dum", LanguageDescription = "Dutch, Middle (ca.1050-1350)" });
            //data.Add(new DimLanguage() { DimLanguageId = 116, LanguageEdFactsCode = "dut", LanguageDescription = "Dutch; Flemish" });
            //data.Add(new DimLanguage() { DimLanguageId = 117, LanguageEdFactsCode = "dyu", LanguageDescription = "Dyula" });
            //data.Add(new DimLanguage() { DimLanguageId = 118, LanguageEdFactsCode = "dzo", LanguageDescription = "Dzongkha" });
            //data.Add(new DimLanguage() { DimLanguageId = 119, LanguageEdFactsCode = "efi", LanguageDescription = "Efik" });
            //data.Add(new DimLanguage() { DimLanguageId = 120, LanguageEdFactsCode = "egy", LanguageDescription = "Egyptian (Ancient)" });
            //data.Add(new DimLanguage() { DimLanguageId = 121, LanguageEdFactsCode = "eka", LanguageDescription = "Ekajuk" });
            //data.Add(new DimLanguage() { DimLanguageId = 122, LanguageEdFactsCode = "elx", LanguageDescription = "Elamite" });
            //data.Add(new DimLanguage() { DimLanguageId = 123, LanguageEdFactsCode = "eng", LanguageDescription = "English" });
            //data.Add(new DimLanguage() { DimLanguageId = 124, LanguageEdFactsCode = "enm", LanguageDescription = "English, Middle (1100-1500)" });
            //data.Add(new DimLanguage() { DimLanguageId = 125, LanguageEdFactsCode = "epo", LanguageDescription = "Esperanto" });
            //data.Add(new DimLanguage() { DimLanguageId = 126, LanguageEdFactsCode = "est", LanguageDescription = "Estonian" });
            //data.Add(new DimLanguage() { DimLanguageId = 127, LanguageEdFactsCode = "ewe", LanguageDescription = "Ewe" });
            //data.Add(new DimLanguage() { DimLanguageId = 128, LanguageEdFactsCode = "ewo", LanguageDescription = "Ewondo" });
            //data.Add(new DimLanguage() { DimLanguageId = 129, LanguageEdFactsCode = "fan", LanguageDescription = "Fang" });
            //data.Add(new DimLanguage() { DimLanguageId = 130, LanguageEdFactsCode = "fao", LanguageDescription = "Faroese" });
            //data.Add(new DimLanguage() { DimLanguageId = 131, LanguageEdFactsCode = "fat", LanguageDescription = "Fanti" });
            //data.Add(new DimLanguage() { DimLanguageId = 132, LanguageEdFactsCode = "fij", LanguageDescription = "Fijian" });
            //data.Add(new DimLanguage() { DimLanguageId = 133, LanguageEdFactsCode = "fil", LanguageDescription = "Filipino; Pilipino" });
            //data.Add(new DimLanguage() { DimLanguageId = 134, LanguageEdFactsCode = "fin", LanguageDescription = "Finnish" });
            //data.Add(new DimLanguage() { DimLanguageId = 135, LanguageEdFactsCode = "fiu", LanguageDescription = "Finno-Ugrian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 136, LanguageEdFactsCode = "fon", LanguageDescription = "Fon" });
            //data.Add(new DimLanguage() { DimLanguageId = 137, LanguageEdFactsCode = "fre", LanguageDescription = "French" });
            //data.Add(new DimLanguage() { DimLanguageId = 138, LanguageEdFactsCode = "frm", LanguageDescription = "French, Middle (ca.1400-1600)" });
            //data.Add(new DimLanguage() { DimLanguageId = 139, LanguageEdFactsCode = "fro", LanguageDescription = "French, Old (842-ca.1400)" });
            //data.Add(new DimLanguage() { DimLanguageId = 140, LanguageEdFactsCode = "frr", LanguageDescription = "Northern Frisian" });
            //data.Add(new DimLanguage() { DimLanguageId = 141, LanguageEdFactsCode = "frs", LanguageDescription = "Eastern Frisian" });
            //data.Add(new DimLanguage() { DimLanguageId = 142, LanguageEdFactsCode = "fry", LanguageDescription = "Western Frisian" });
            //data.Add(new DimLanguage() { DimLanguageId = 143, LanguageEdFactsCode = "ful", LanguageDescription = "Fulah" });
            //data.Add(new DimLanguage() { DimLanguageId = 144, LanguageEdFactsCode = "fur", LanguageDescription = "Friulian" });
            //data.Add(new DimLanguage() { DimLanguageId = 145, LanguageEdFactsCode = "gaa", LanguageDescription = "Ga" });
            //data.Add(new DimLanguage() { DimLanguageId = 146, LanguageEdFactsCode = "gay", LanguageDescription = "Gayo" });
            //data.Add(new DimLanguage() { DimLanguageId = 147, LanguageEdFactsCode = "gba", LanguageDescription = "Gbaya" });
            //data.Add(new DimLanguage() { DimLanguageId = 148, LanguageEdFactsCode = "gem", LanguageDescription = "Germanic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 149, LanguageEdFactsCode = "geo", LanguageDescription = "Georgian" });
            //data.Add(new DimLanguage() { DimLanguageId = 150, LanguageEdFactsCode = "ger", LanguageDescription = "German" });
            //data.Add(new DimLanguage() { DimLanguageId = 151, LanguageEdFactsCode = "gez", LanguageDescription = "Geez" });
            //data.Add(new DimLanguage() { DimLanguageId = 152, LanguageEdFactsCode = "gil", LanguageDescription = "Gilbertese" });
            //data.Add(new DimLanguage() { DimLanguageId = 153, LanguageEdFactsCode = "gla", LanguageDescription = "Gaelic; Scottish Gaelic" });
            //data.Add(new DimLanguage() { DimLanguageId = 154, LanguageEdFactsCode = "gle", LanguageDescription = "Irish" });
            //data.Add(new DimLanguage() { DimLanguageId = 155, LanguageEdFactsCode = "glg", LanguageDescription = "Galician" });
            //data.Add(new DimLanguage() { DimLanguageId = 156, LanguageEdFactsCode = "glv", LanguageDescription = "Manx" });
            //data.Add(new DimLanguage() { DimLanguageId = 157, LanguageEdFactsCode = "gmh", LanguageDescription = "German, Middle High (ca.1050-1500)" });
            //data.Add(new DimLanguage() { DimLanguageId = 158, LanguageEdFactsCode = "goh", LanguageDescription = "German, Old High (ca.750-1050)" });
            //data.Add(new DimLanguage() { DimLanguageId = 159, LanguageEdFactsCode = "gon", LanguageDescription = "Gondi" });
            //data.Add(new DimLanguage() { DimLanguageId = 160, LanguageEdFactsCode = "gor", LanguageDescription = "Gorontalo" });
            //data.Add(new DimLanguage() { DimLanguageId = 161, LanguageEdFactsCode = "got", LanguageDescription = "Gothic" });
            //data.Add(new DimLanguage() { DimLanguageId = 162, LanguageEdFactsCode = "grb", LanguageDescription = "Grebo" });
            //data.Add(new DimLanguage() { DimLanguageId = 163, LanguageEdFactsCode = "grc", LanguageDescription = "Greek, Ancient (to 1453)" });
            //data.Add(new DimLanguage() { DimLanguageId = 164, LanguageEdFactsCode = "gre", LanguageDescription = "Greek, Modern (1453-)" });
            //data.Add(new DimLanguage() { DimLanguageId = 165, LanguageEdFactsCode = "grn", LanguageDescription = "Guarani" });
            //data.Add(new DimLanguage() { DimLanguageId = 166, LanguageEdFactsCode = "gsw", LanguageDescription = "Swiss German; Alemannic; Alsatian" });
            //data.Add(new DimLanguage() { DimLanguageId = 167, LanguageEdFactsCode = "guj", LanguageDescription = "Gujarati" });
            //data.Add(new DimLanguage() { DimLanguageId = 168, LanguageEdFactsCode = "gwi", LanguageDescription = "Gwich'in" });
            //data.Add(new DimLanguage() { DimLanguageId = 169, LanguageEdFactsCode = "hai", LanguageDescription = "Haida" });
            //data.Add(new DimLanguage() { DimLanguageId = 170, LanguageEdFactsCode = "hat", LanguageDescription = "Haitian; Haitian Creole" });
            //data.Add(new DimLanguage() { DimLanguageId = 171, LanguageEdFactsCode = "hau", LanguageDescription = "Hausa" });
            //data.Add(new DimLanguage() { DimLanguageId = 172, LanguageEdFactsCode = "haw", LanguageDescription = "Hawaiian" });
            //data.Add(new DimLanguage() { DimLanguageId = 173, LanguageEdFactsCode = "heb", LanguageDescription = "Hebrew" });
            //data.Add(new DimLanguage() { DimLanguageId = 174, LanguageEdFactsCode = "her", LanguageDescription = "Herero" });
            //data.Add(new DimLanguage() { DimLanguageId = 175, LanguageEdFactsCode = "hil", LanguageDescription = "Hiligaynon" });
            //data.Add(new DimLanguage() { DimLanguageId = 176, LanguageEdFactsCode = "him", LanguageDescription = "Himachali languages; Western Pahari languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 177, LanguageEdFactsCode = "hin", LanguageDescription = "Hindi" });
            //data.Add(new DimLanguage() { DimLanguageId = 178, LanguageEdFactsCode = "hit", LanguageDescription = "Hittite" });
            //data.Add(new DimLanguage() { DimLanguageId = 179, LanguageEdFactsCode = "hmn", LanguageDescription = "Hmong; Mong" });
            //data.Add(new DimLanguage() { DimLanguageId = 180, LanguageEdFactsCode = "hmo", LanguageDescription = "Hiri Motu" });
            //data.Add(new DimLanguage() { DimLanguageId = 181, LanguageEdFactsCode = "hrv", LanguageDescription = "Croatian" });
            //data.Add(new DimLanguage() { DimLanguageId = 182, LanguageEdFactsCode = "hsb", LanguageDescription = "Upper Sorbian" });
            //data.Add(new DimLanguage() { DimLanguageId = 183, LanguageEdFactsCode = "hun", LanguageDescription = "Hungarian" });
            //data.Add(new DimLanguage() { DimLanguageId = 184, LanguageEdFactsCode = "hup", LanguageDescription = "Hupa" });
            //data.Add(new DimLanguage() { DimLanguageId = 185, LanguageEdFactsCode = "iba", LanguageDescription = "Iban" });
            //data.Add(new DimLanguage() { DimLanguageId = 186, LanguageEdFactsCode = "ibo", LanguageDescription = "Igbo" });
            //data.Add(new DimLanguage() { DimLanguageId = 187, LanguageEdFactsCode = "ice", LanguageDescription = "Icelandic" });
            //data.Add(new DimLanguage() { DimLanguageId = 188, LanguageEdFactsCode = "ido", LanguageDescription = "Ido" });
            //data.Add(new DimLanguage() { DimLanguageId = 189, LanguageEdFactsCode = "iii", LanguageDescription = "Sichuan Yi; Nuosu" });
            //data.Add(new DimLanguage() { DimLanguageId = 190, LanguageEdFactsCode = "ijo", LanguageDescription = "Ijo languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 191, LanguageEdFactsCode = "iku", LanguageDescription = "Inuktitut" });
            //data.Add(new DimLanguage() { DimLanguageId = 192, LanguageEdFactsCode = "ile", LanguageDescription = "Interlingue; Occidental" });
            //data.Add(new DimLanguage() { DimLanguageId = 193, LanguageEdFactsCode = "ilo", LanguageDescription = "Iloko" });
            //data.Add(new DimLanguage() { DimLanguageId = 194, LanguageEdFactsCode = "ina", LanguageDescription = "Interlingua (International Auxiliary Language Association)" });
            //data.Add(new DimLanguage() { DimLanguageId = 195, LanguageEdFactsCode = "inc", LanguageDescription = "Indic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 196, LanguageEdFactsCode = "ind", LanguageDescription = "Indonesian" });
            //data.Add(new DimLanguage() { DimLanguageId = 197, LanguageEdFactsCode = "ine", LanguageDescription = "Indo-European languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 198, LanguageEdFactsCode = "inh", LanguageDescription = "Ingush" });
            //data.Add(new DimLanguage() { DimLanguageId = 199, LanguageEdFactsCode = "ipk", LanguageDescription = "Inupiaq" });
            //data.Add(new DimLanguage() { DimLanguageId = 200, LanguageEdFactsCode = "ira", LanguageDescription = "Iranian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 201, LanguageEdFactsCode = "iro", LanguageDescription = "Iroquoian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 202, LanguageEdFactsCode = "ita", LanguageDescription = "Italian" });
            //data.Add(new DimLanguage() { DimLanguageId = 203, LanguageEdFactsCode = "jav", LanguageDescription = "Javanese" });
            //data.Add(new DimLanguage() { DimLanguageId = 204, LanguageEdFactsCode = "jbo", LanguageDescription = "Lojban" });
            //data.Add(new DimLanguage() { DimLanguageId = 205, LanguageEdFactsCode = "jpn", LanguageDescription = "Japanese" });
            //data.Add(new DimLanguage() { DimLanguageId = 206, LanguageEdFactsCode = "jpr", LanguageDescription = "Judeo-Persian" });
            //data.Add(new DimLanguage() { DimLanguageId = 207, LanguageEdFactsCode = "jrb", LanguageDescription = "Judeo-Arabic" });
            //data.Add(new DimLanguage() { DimLanguageId = 208, LanguageEdFactsCode = "kaa", LanguageDescription = "Kara-Kalpak" });
            //data.Add(new DimLanguage() { DimLanguageId = 209, LanguageEdFactsCode = "kab", LanguageDescription = "Kabyle" });
            //data.Add(new DimLanguage() { DimLanguageId = 210, LanguageEdFactsCode = "kac", LanguageDescription = "Kachin; Jingpho" });
            //data.Add(new DimLanguage() { DimLanguageId = 211, LanguageEdFactsCode = "kal", LanguageDescription = "Kalaallisut; Greenlandic" });
            //data.Add(new DimLanguage() { DimLanguageId = 212, LanguageEdFactsCode = "kam", LanguageDescription = "Kamba" });
            //data.Add(new DimLanguage() { DimLanguageId = 213, LanguageEdFactsCode = "kan", LanguageDescription = "Kannada" });
            //data.Add(new DimLanguage() { DimLanguageId = 214, LanguageEdFactsCode = "kar", LanguageDescription = "Karen languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 215, LanguageEdFactsCode = "kas", LanguageDescription = "Kashmiri" });
            //data.Add(new DimLanguage() { DimLanguageId = 216, LanguageEdFactsCode = "kau", LanguageDescription = "Kanuri" });
            //data.Add(new DimLanguage() { DimLanguageId = 217, LanguageEdFactsCode = "kaw", LanguageDescription = "Kawi" });
            //data.Add(new DimLanguage() { DimLanguageId = 218, LanguageEdFactsCode = "kaz", LanguageDescription = "Kazakh" });
            //data.Add(new DimLanguage() { DimLanguageId = 219, LanguageEdFactsCode = "kbd", LanguageDescription = "Kabardian" });
            //data.Add(new DimLanguage() { DimLanguageId = 220, LanguageEdFactsCode = "kha", LanguageDescription = "Khasi" });
            //data.Add(new DimLanguage() { DimLanguageId = 221, LanguageEdFactsCode = "khi", LanguageDescription = "Khoisan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 222, LanguageEdFactsCode = "khm", LanguageDescription = "Central Khmer" });
            //data.Add(new DimLanguage() { DimLanguageId = 223, LanguageEdFactsCode = "kho", LanguageDescription = "Khotanese; Sakan" });
            //data.Add(new DimLanguage() { DimLanguageId = 224, LanguageEdFactsCode = "kik", LanguageDescription = "Kikuyu; Gikuyu" });
            //data.Add(new DimLanguage() { DimLanguageId = 225, LanguageEdFactsCode = "kin", LanguageDescription = "Kinyarwanda" });
            //data.Add(new DimLanguage() { DimLanguageId = 226, LanguageEdFactsCode = "kir", LanguageDescription = "Kirghiz; Kyrgyz" });
            //data.Add(new DimLanguage() { DimLanguageId = 227, LanguageEdFactsCode = "kmb", LanguageDescription = "Kimbundu" });
            //data.Add(new DimLanguage() { DimLanguageId = 228, LanguageEdFactsCode = "kok", LanguageDescription = "Konkani" });
            //data.Add(new DimLanguage() { DimLanguageId = 229, LanguageEdFactsCode = "kom", LanguageDescription = "Komi" });
            //data.Add(new DimLanguage() { DimLanguageId = 230, LanguageEdFactsCode = "kon", LanguageDescription = "Kongo" });
            //data.Add(new DimLanguage() { DimLanguageId = 231, LanguageEdFactsCode = "kor", LanguageDescription = "Korean" });
            //data.Add(new DimLanguage() { DimLanguageId = 232, LanguageEdFactsCode = "kos", LanguageDescription = "Kosraean" });
            //data.Add(new DimLanguage() { DimLanguageId = 233, LanguageEdFactsCode = "kpe", LanguageDescription = "Kpelle" });
            //data.Add(new DimLanguage() { DimLanguageId = 234, LanguageEdFactsCode = "krc", LanguageDescription = "Karachay-Balkar" });
            //data.Add(new DimLanguage() { DimLanguageId = 235, LanguageEdFactsCode = "krl", LanguageDescription = "Karelian" });
            //data.Add(new DimLanguage() { DimLanguageId = 236, LanguageEdFactsCode = "kro", LanguageDescription = "Kru languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 237, LanguageEdFactsCode = "kru", LanguageDescription = "Kurukh" });
            //data.Add(new DimLanguage() { DimLanguageId = 238, LanguageEdFactsCode = "kua", LanguageDescription = "Kuanyama; Kwanyama" });
            //data.Add(new DimLanguage() { DimLanguageId = 239, LanguageEdFactsCode = "kum", LanguageDescription = "Kumyk" });
            //data.Add(new DimLanguage() { DimLanguageId = 240, LanguageEdFactsCode = "kur", LanguageDescription = "Kurdish" });
            //data.Add(new DimLanguage() { DimLanguageId = 241, LanguageEdFactsCode = "kut", LanguageDescription = "Kutenai" });
            //data.Add(new DimLanguage() { DimLanguageId = 242, LanguageEdFactsCode = "lad", LanguageDescription = "Ladino" });
            //data.Add(new DimLanguage() { DimLanguageId = 243, LanguageEdFactsCode = "lah", LanguageDescription = "Lahnda" });
            //data.Add(new DimLanguage() { DimLanguageId = 244, LanguageEdFactsCode = "lam", LanguageDescription = "Lamba" });
            //data.Add(new DimLanguage() { DimLanguageId = 245, LanguageEdFactsCode = "lao", LanguageDescription = "Lao" });
            //data.Add(new DimLanguage() { DimLanguageId = 246, LanguageEdFactsCode = "lat", LanguageDescription = "Latin" });
            //data.Add(new DimLanguage() { DimLanguageId = 247, LanguageEdFactsCode = "lav", LanguageDescription = "Latvian" });
            //data.Add(new DimLanguage() { DimLanguageId = 248, LanguageEdFactsCode = "lez", LanguageDescription = "Lezghian" });
            //data.Add(new DimLanguage() { DimLanguageId = 249, LanguageEdFactsCode = "lim", LanguageDescription = "Limburgan; Limburger; Limburgish" });
            //data.Add(new DimLanguage() { DimLanguageId = 250, LanguageEdFactsCode = "lin", LanguageDescription = "Lingala" });
            //data.Add(new DimLanguage() { DimLanguageId = 251, LanguageEdFactsCode = "lit", LanguageDescription = "Lithuanian" });
            //data.Add(new DimLanguage() { DimLanguageId = 252, LanguageEdFactsCode = "lol", LanguageDescription = "Mongo" });
            //data.Add(new DimLanguage() { DimLanguageId = 253, LanguageEdFactsCode = "loz", LanguageDescription = "Lozi" });
            //data.Add(new DimLanguage() { DimLanguageId = 254, LanguageEdFactsCode = "ltz", LanguageDescription = "Luxembourgish; Letzeburgesch" });
            //data.Add(new DimLanguage() { DimLanguageId = 255, LanguageEdFactsCode = "lua", LanguageDescription = "Luba-Lulua" });
            //data.Add(new DimLanguage() { DimLanguageId = 256, LanguageEdFactsCode = "lub", LanguageDescription = "Luba-Katanga" });
            //data.Add(new DimLanguage() { DimLanguageId = 257, LanguageEdFactsCode = "lug", LanguageDescription = "Ganda" });
            //data.Add(new DimLanguage() { DimLanguageId = 258, LanguageEdFactsCode = "lui", LanguageDescription = "Luiseno" });
            //data.Add(new DimLanguage() { DimLanguageId = 259, LanguageEdFactsCode = "lun", LanguageDescription = "Lunda" });
            //data.Add(new DimLanguage() { DimLanguageId = 260, LanguageEdFactsCode = "luo", LanguageDescription = "Luo (Kenya and Tanzania)" });
            //data.Add(new DimLanguage() { DimLanguageId = 261, LanguageEdFactsCode = "lus", LanguageDescription = "Lushai" });
            //data.Add(new DimLanguage() { DimLanguageId = 262, LanguageEdFactsCode = "mac", LanguageDescription = "Macedonian" });
            //data.Add(new DimLanguage() { DimLanguageId = 263, LanguageEdFactsCode = "mad", LanguageDescription = "Madurese" });
            //data.Add(new DimLanguage() { DimLanguageId = 264, LanguageEdFactsCode = "mag", LanguageDescription = "Magahi" });
            //data.Add(new DimLanguage() { DimLanguageId = 265, LanguageEdFactsCode = "mah", LanguageDescription = "Marshallese" });
            //data.Add(new DimLanguage() { DimLanguageId = 266, LanguageEdFactsCode = "mai", LanguageDescription = "Maithili" });
            //data.Add(new DimLanguage() { DimLanguageId = 267, LanguageEdFactsCode = "mak", LanguageDescription = "Makasar" });
            //data.Add(new DimLanguage() { DimLanguageId = 268, LanguageEdFactsCode = "mal", LanguageDescription = "Malayalam" });
            //data.Add(new DimLanguage() { DimLanguageId = 269, LanguageEdFactsCode = "man", LanguageDescription = "Mandingo" });
            //data.Add(new DimLanguage() { DimLanguageId = 270, LanguageEdFactsCode = "mao", LanguageDescription = "Maori" });
            //data.Add(new DimLanguage() { DimLanguageId = 271, LanguageEdFactsCode = "map", LanguageDescription = "Austronesian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 272, LanguageEdFactsCode = "mar", LanguageDescription = "Marathi" });
            //data.Add(new DimLanguage() { DimLanguageId = 273, LanguageEdFactsCode = "mas", LanguageDescription = "Masai" });
            //data.Add(new DimLanguage() { DimLanguageId = 274, LanguageEdFactsCode = "may", LanguageDescription = "Malay" });
            //data.Add(new DimLanguage() { DimLanguageId = 275, LanguageEdFactsCode = "mdf", LanguageDescription = "Moksha" });
            //data.Add(new DimLanguage() { DimLanguageId = 276, LanguageEdFactsCode = "mdr", LanguageDescription = "Mandar" });
            //data.Add(new DimLanguage() { DimLanguageId = 277, LanguageEdFactsCode = "men", LanguageDescription = "Mende" });
            //data.Add(new DimLanguage() { DimLanguageId = 278, LanguageEdFactsCode = "mga", LanguageDescription = "Irish, Middle (900-1200)" });
            //data.Add(new DimLanguage() { DimLanguageId = 279, LanguageEdFactsCode = "mic", LanguageDescription = "Mi'kmaq; Micmac" });
            //data.Add(new DimLanguage() { DimLanguageId = 280, LanguageEdFactsCode = "min", LanguageDescription = "Minangkabau" });
            //data.Add(new DimLanguage() { DimLanguageId = 281, LanguageEdFactsCode = "mis", LanguageDescription = "Uncoded languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 282, LanguageEdFactsCode = "mkh", LanguageDescription = "Mon-Khmer languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 283, LanguageEdFactsCode = "mlg", LanguageDescription = "Malagasy" });
            //data.Add(new DimLanguage() { DimLanguageId = 284, LanguageEdFactsCode = "mlt", LanguageDescription = "Maltese" });
            //data.Add(new DimLanguage() { DimLanguageId = 285, LanguageEdFactsCode = "mnc", LanguageDescription = "Manchu" });
            //data.Add(new DimLanguage() { DimLanguageId = 286, LanguageEdFactsCode = "mni", LanguageDescription = "Manipuri" });
            //data.Add(new DimLanguage() { DimLanguageId = 287, LanguageEdFactsCode = "mno", LanguageDescription = "Manobo languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 288, LanguageEdFactsCode = "moh", LanguageDescription = "Mohawk" });
            //data.Add(new DimLanguage() { DimLanguageId = 289, LanguageEdFactsCode = "mon", LanguageDescription = "Mongolian" });
            //data.Add(new DimLanguage() { DimLanguageId = 290, LanguageEdFactsCode = "mos", LanguageDescription = "Mossi" });
            //data.Add(new DimLanguage() { DimLanguageId = 291, LanguageEdFactsCode = "mul", LanguageDescription = "Multiple languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 292, LanguageEdFactsCode = "mun", LanguageDescription = "Munda languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 293, LanguageEdFactsCode = "mus", LanguageDescription = "Creek" });
            //data.Add(new DimLanguage() { DimLanguageId = 294, LanguageEdFactsCode = "mwl", LanguageDescription = "Mirandese" });
            //data.Add(new DimLanguage() { DimLanguageId = 295, LanguageEdFactsCode = "mwr", LanguageDescription = "Marwari" });
            //data.Add(new DimLanguage() { DimLanguageId = 296, LanguageEdFactsCode = "myn", LanguageDescription = "Mayan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 297, LanguageEdFactsCode = "myv", LanguageDescription = "Erzya" });
            //data.Add(new DimLanguage() { DimLanguageId = 298, LanguageEdFactsCode = "nah", LanguageDescription = "Nahuatl languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 299, LanguageEdFactsCode = "nai", LanguageDescription = "North American Indian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 300, LanguageEdFactsCode = "nap", LanguageDescription = "Neapolitan" });
            //data.Add(new DimLanguage() { DimLanguageId = 301, LanguageEdFactsCode = "nau", LanguageDescription = "Nauru" });
            //data.Add(new DimLanguage() { DimLanguageId = 302, LanguageEdFactsCode = "nav", LanguageDescription = "Navajo; Navaho" });
            //data.Add(new DimLanguage() { DimLanguageId = 303, LanguageEdFactsCode = "nbl", LanguageDescription = "Ndebele, South; South Ndebele" });
            //data.Add(new DimLanguage() { DimLanguageId = 304, LanguageEdFactsCode = "nde", LanguageDescription = "Ndebele, North; North Ndebele" });
            //data.Add(new DimLanguage() { DimLanguageId = 305, LanguageEdFactsCode = "ndo", LanguageDescription = "Ndonga" });
            //data.Add(new DimLanguage() { DimLanguageId = 306, LanguageEdFactsCode = "nds", LanguageDescription = "Low German; Low Saxon; German, Low; Saxon, Low" });
            //data.Add(new DimLanguage() { DimLanguageId = 307, LanguageEdFactsCode = "nep", LanguageDescription = "Nepali" });
            //data.Add(new DimLanguage() { DimLanguageId = 308, LanguageEdFactsCode = "new", LanguageDescription = "Nepal Bhasa; Newari" });
            //data.Add(new DimLanguage() { DimLanguageId = 309, LanguageEdFactsCode = "nia", LanguageDescription = "Nias" });
            //data.Add(new DimLanguage() { DimLanguageId = 310, LanguageEdFactsCode = "nic", LanguageDescription = "Niger-Kordofanian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 311, LanguageEdFactsCode = "niu", LanguageDescription = "Niuean" });
            //data.Add(new DimLanguage() { DimLanguageId = 312, LanguageEdFactsCode = "nno", LanguageDescription = "Norwegian Nynorsk; Nynorsk, Norwegian" });
            //data.Add(new DimLanguage() { DimLanguageId = 313, LanguageEdFactsCode = "nob", LanguageDescription = "Bokm?l, Norwegian; Norwegian Bokm?l" });
            //data.Add(new DimLanguage() { DimLanguageId = 314, LanguageEdFactsCode = "nog", LanguageDescription = "Nogai" });
            //data.Add(new DimLanguage() { DimLanguageId = 315, LanguageEdFactsCode = "non", LanguageDescription = "Norse, Old" });
            //data.Add(new DimLanguage() { DimLanguageId = 316, LanguageEdFactsCode = "nor", LanguageDescription = "Norwegian" });
            //data.Add(new DimLanguage() { DimLanguageId = 317, LanguageEdFactsCode = "nqo", LanguageDescription = "N'Ko" });
            //data.Add(new DimLanguage() { DimLanguageId = 318, LanguageEdFactsCode = "nso", LanguageDescription = "Pedi; Sepedi; Northern Sotho" });
            //data.Add(new DimLanguage() { DimLanguageId = 319, LanguageEdFactsCode = "nub", LanguageDescription = "Nubian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 320, LanguageEdFactsCode = "nwc", LanguageDescription = "Classical Newari; Old Newari; Classical Nepal Bhasa" });
            //data.Add(new DimLanguage() { DimLanguageId = 321, LanguageEdFactsCode = "nya", LanguageDescription = "Chichewa; Chewa; Nyanja" });
            //data.Add(new DimLanguage() { DimLanguageId = 322, LanguageEdFactsCode = "nym", LanguageDescription = "Nyamwezi" });
            //data.Add(new DimLanguage() { DimLanguageId = 323, LanguageEdFactsCode = "nyn", LanguageDescription = "Nyankole" });
            //data.Add(new DimLanguage() { DimLanguageId = 324, LanguageEdFactsCode = "nyo", LanguageDescription = "Nyoro" });
            //data.Add(new DimLanguage() { DimLanguageId = 325, LanguageEdFactsCode = "nzi", LanguageDescription = "Nzima" });
            //data.Add(new DimLanguage() { DimLanguageId = 326, LanguageEdFactsCode = "oci", LanguageDescription = "Occitan (post 1500)" });
            //data.Add(new DimLanguage() { DimLanguageId = 327, LanguageEdFactsCode = "oji", LanguageDescription = "Ojibwa" });
            //data.Add(new DimLanguage() { DimLanguageId = 328, LanguageEdFactsCode = "ori", LanguageDescription = "Oriya" });
            //data.Add(new DimLanguage() { DimLanguageId = 329, LanguageEdFactsCode = "orm", LanguageDescription = "Oromo" });
            //data.Add(new DimLanguage() { DimLanguageId = 330, LanguageEdFactsCode = "osa", LanguageDescription = "Osage" });
            //data.Add(new DimLanguage() { DimLanguageId = 331, LanguageEdFactsCode = "oss", LanguageDescription = "Ossetian; Ossetic" });
            //data.Add(new DimLanguage() { DimLanguageId = 332, LanguageEdFactsCode = "ota", LanguageDescription = "Turkish, Ottoman (1500-1928)" });
            //data.Add(new DimLanguage() { DimLanguageId = 333, LanguageEdFactsCode = "oto", LanguageDescription = "Otomian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 334, LanguageEdFactsCode = "paa", LanguageDescription = "Papuan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 335, LanguageEdFactsCode = "pag", LanguageDescription = "Pangasinan" });
            //data.Add(new DimLanguage() { DimLanguageId = 336, LanguageEdFactsCode = "pal", LanguageDescription = "Pahlavi" });
            //data.Add(new DimLanguage() { DimLanguageId = 337, LanguageEdFactsCode = "pam", LanguageDescription = "Pampanga; Kapampangan" });
            //data.Add(new DimLanguage() { DimLanguageId = 338, LanguageEdFactsCode = "pan", LanguageDescription = "Panjabi; Punjabi" });
            //data.Add(new DimLanguage() { DimLanguageId = 339, LanguageEdFactsCode = "pap", LanguageDescription = "Papiamento" });
            //data.Add(new DimLanguage() { DimLanguageId = 340, LanguageEdFactsCode = "pau", LanguageDescription = "Palauan" });
            //data.Add(new DimLanguage() { DimLanguageId = 341, LanguageEdFactsCode = "peo", LanguageDescription = "Persian, Old (ca.600-400 B.C.)" });
            //data.Add(new DimLanguage() { DimLanguageId = 342, LanguageEdFactsCode = "per", LanguageDescription = "Persian" });
            //data.Add(new DimLanguage() { DimLanguageId = 343, LanguageEdFactsCode = "phi", LanguageDescription = "Philippine languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 344, LanguageEdFactsCode = "phn", LanguageDescription = "Phoenician" });
            //data.Add(new DimLanguage() { DimLanguageId = 345, LanguageEdFactsCode = "pli", LanguageDescription = "Pali" });
            //data.Add(new DimLanguage() { DimLanguageId = 346, LanguageEdFactsCode = "pol", LanguageDescription = "Polish" });
            //data.Add(new DimLanguage() { DimLanguageId = 347, LanguageEdFactsCode = "pon", LanguageDescription = "Pohnpeian" });
            //data.Add(new DimLanguage() { DimLanguageId = 348, LanguageEdFactsCode = "por", LanguageDescription = "Portuguese" });
            //data.Add(new DimLanguage() { DimLanguageId = 349, LanguageEdFactsCode = "pra", LanguageDescription = "Prakrit languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 350, LanguageEdFactsCode = "pro", LanguageDescription = "Proven?al, Old (to 1500); Occitan, Old (to 1500)" });
            //data.Add(new DimLanguage() { DimLanguageId = 351, LanguageEdFactsCode = "pus", LanguageDescription = "Pushto; Pashto" });
            //data.Add(new DimLanguage() { DimLanguageId = 352, LanguageEdFactsCode = "que", LanguageDescription = "Quechua" });
            //data.Add(new DimLanguage() { DimLanguageId = 353, LanguageEdFactsCode = "raj", LanguageDescription = "Rajasthani" });
            //data.Add(new DimLanguage() { DimLanguageId = 354, LanguageEdFactsCode = "rap", LanguageDescription = "Rapanui" });
            //data.Add(new DimLanguage() { DimLanguageId = 355, LanguageEdFactsCode = "rar", LanguageDescription = "Rarotongan; Cook Islands Maori" });
            //data.Add(new DimLanguage() { DimLanguageId = 356, LanguageEdFactsCode = "roa", LanguageDescription = "Romance languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 357, LanguageEdFactsCode = "roh", LanguageDescription = "Romansh" });
            //data.Add(new DimLanguage() { DimLanguageId = 358, LanguageEdFactsCode = "rom", LanguageDescription = "Romany" });
            //data.Add(new DimLanguage() { DimLanguageId = 359, LanguageEdFactsCode = "rum", LanguageDescription = "Romanian" });
            //data.Add(new DimLanguage() { DimLanguageId = 360, LanguageEdFactsCode = "run", LanguageDescription = "Rundi" });
            //data.Add(new DimLanguage() { DimLanguageId = 361, LanguageEdFactsCode = "rup", LanguageDescription = "Aromanian; Arumanian; Macedo-Romanian" });
            //data.Add(new DimLanguage() { DimLanguageId = 362, LanguageEdFactsCode = "rus", LanguageDescription = "Russian" });
            //data.Add(new DimLanguage() { DimLanguageId = 363, LanguageEdFactsCode = "sad", LanguageDescription = "Sandawe" });
            //data.Add(new DimLanguage() { DimLanguageId = 364, LanguageEdFactsCode = "sag", LanguageDescription = "Sango" });
            //data.Add(new DimLanguage() { DimLanguageId = 365, LanguageEdFactsCode = "sah", LanguageDescription = "Yakut" });
            //data.Add(new DimLanguage() { DimLanguageId = 366, LanguageEdFactsCode = "sai", LanguageDescription = "South American Indian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 367, LanguageEdFactsCode = "sal", LanguageDescription = "Salishan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 368, LanguageEdFactsCode = "sam", LanguageDescription = "Samaritan Aramaic" });
            //data.Add(new DimLanguage() { DimLanguageId = 369, LanguageEdFactsCode = "san", LanguageDescription = "Sanskrit" });
            //data.Add(new DimLanguage() { DimLanguageId = 370, LanguageEdFactsCode = "sas", LanguageDescription = "Sasak" });
            //data.Add(new DimLanguage() { DimLanguageId = 371, LanguageEdFactsCode = "sat", LanguageDescription = "Santali" });
            //data.Add(new DimLanguage() { DimLanguageId = 372, LanguageEdFactsCode = "scn", LanguageDescription = "Sicilian" });
            //data.Add(new DimLanguage() { DimLanguageId = 373, LanguageEdFactsCode = "sco", LanguageDescription = "Scots" });
            //data.Add(new DimLanguage() { DimLanguageId = 374, LanguageEdFactsCode = "sel", LanguageDescription = "Selkup" });
            //data.Add(new DimLanguage() { DimLanguageId = 375, LanguageEdFactsCode = "sem", LanguageDescription = "Semitic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 376, LanguageEdFactsCode = "sga", LanguageDescription = "Irish, Old (to 900)" });
            //data.Add(new DimLanguage() { DimLanguageId = 377, LanguageEdFactsCode = "sgn", LanguageDescription = "Sign Languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 378, LanguageEdFactsCode = "shn", LanguageDescription = "Shan" });
            //data.Add(new DimLanguage() { DimLanguageId = 379, LanguageEdFactsCode = "sid", LanguageDescription = "Sidamo" });
            //data.Add(new DimLanguage() { DimLanguageId = 380, LanguageEdFactsCode = "sin", LanguageDescription = "Sinhala; Sinhalese" });
            //data.Add(new DimLanguage() { DimLanguageId = 381, LanguageEdFactsCode = "sio", LanguageDescription = "Siouan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 382, LanguageEdFactsCode = "sit", LanguageDescription = "Sino-Tibetan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 383, LanguageEdFactsCode = "sla", LanguageDescription = "Slavic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 384, LanguageEdFactsCode = "slo", LanguageDescription = "Slovak" });
            //data.Add(new DimLanguage() { DimLanguageId = 385, LanguageEdFactsCode = "slv", LanguageDescription = "Slovenian" });
            //data.Add(new DimLanguage() { DimLanguageId = 386, LanguageEdFactsCode = "sma", LanguageDescription = "Southern Sami" });
            //data.Add(new DimLanguage() { DimLanguageId = 387, LanguageEdFactsCode = "sme", LanguageDescription = "Northern Sami" });
            //data.Add(new DimLanguage() { DimLanguageId = 388, LanguageEdFactsCode = "smi", LanguageDescription = "Sami languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 389, LanguageEdFactsCode = "smj", LanguageDescription = "Lule Sami" });
            //data.Add(new DimLanguage() { DimLanguageId = 390, LanguageEdFactsCode = "smn", LanguageDescription = "Inari Sami" });
            //data.Add(new DimLanguage() { DimLanguageId = 391, LanguageEdFactsCode = "smo", LanguageDescription = "Samoan" });
            //data.Add(new DimLanguage() { DimLanguageId = 392, LanguageEdFactsCode = "sms", LanguageDescription = "Skolt Sami" });
            //data.Add(new DimLanguage() { DimLanguageId = 393, LanguageEdFactsCode = "sna", LanguageDescription = "Shona" });
            //data.Add(new DimLanguage() { DimLanguageId = 394, LanguageEdFactsCode = "snd", LanguageDescription = "Sindhi" });
            //data.Add(new DimLanguage() { DimLanguageId = 395, LanguageEdFactsCode = "snk", LanguageDescription = "Soninke" });
            //data.Add(new DimLanguage() { DimLanguageId = 396, LanguageEdFactsCode = "sog", LanguageDescription = "Sogdian" });
            //data.Add(new DimLanguage() { DimLanguageId = 397, LanguageEdFactsCode = "som", LanguageDescription = "Somali" });
            //data.Add(new DimLanguage() { DimLanguageId = 398, LanguageEdFactsCode = "son", LanguageDescription = "Songhai languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 399, LanguageEdFactsCode = "sot", LanguageDescription = "Sotho, Southern" });
            //data.Add(new DimLanguage() { DimLanguageId = 400, LanguageEdFactsCode = "spa", LanguageDescription = "Spanish; Castilian" });
            //data.Add(new DimLanguage() { DimLanguageId = 401, LanguageEdFactsCode = "srd", LanguageDescription = "Sardinian" });
            //data.Add(new DimLanguage() { DimLanguageId = 402, LanguageEdFactsCode = "srn", LanguageDescription = "Sranan Tongo" });
            //data.Add(new DimLanguage() { DimLanguageId = 403, LanguageEdFactsCode = "srp", LanguageDescription = "Serbian" });
            //data.Add(new DimLanguage() { DimLanguageId = 404, LanguageEdFactsCode = "srr", LanguageDescription = "Serer" });
            //data.Add(new DimLanguage() { DimLanguageId = 405, LanguageEdFactsCode = "ssa", LanguageDescription = "Nilo-Saharan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 406, LanguageEdFactsCode = "ssw", LanguageDescription = "Swati" });
            //data.Add(new DimLanguage() { DimLanguageId = 407, LanguageEdFactsCode = "suk", LanguageDescription = "Sukuma" });
            //data.Add(new DimLanguage() { DimLanguageId = 408, LanguageEdFactsCode = "sun", LanguageDescription = "Sundanese" });
            //data.Add(new DimLanguage() { DimLanguageId = 409, LanguageEdFactsCode = "sus", LanguageDescription = "Susu" });
            //data.Add(new DimLanguage() { DimLanguageId = 410, LanguageEdFactsCode = "sux", LanguageDescription = "Sumerian" });
            //data.Add(new DimLanguage() { DimLanguageId = 411, LanguageEdFactsCode = "swa", LanguageDescription = "Swahili" });
            //data.Add(new DimLanguage() { DimLanguageId = 412, LanguageEdFactsCode = "swe", LanguageDescription = "Swedish" });
            //data.Add(new DimLanguage() { DimLanguageId = 413, LanguageEdFactsCode = "syc", LanguageDescription = "Classical Syriac" });
            //data.Add(new DimLanguage() { DimLanguageId = 414, LanguageEdFactsCode = "syr", LanguageDescription = "Syriac" });
            //data.Add(new DimLanguage() { DimLanguageId = 415, LanguageEdFactsCode = "tah", LanguageDescription = "Tahitian" });
            //data.Add(new DimLanguage() { DimLanguageId = 416, LanguageEdFactsCode = "tai", LanguageDescription = "Tai languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 417, LanguageEdFactsCode = "tam", LanguageDescription = "Tamil" });
            //data.Add(new DimLanguage() { DimLanguageId = 418, LanguageEdFactsCode = "tat", LanguageDescription = "Tatar" });
            //data.Add(new DimLanguage() { DimLanguageId = 419, LanguageEdFactsCode = "tel", LanguageDescription = "Telugu" });
            //data.Add(new DimLanguage() { DimLanguageId = 420, LanguageEdFactsCode = "tem", LanguageDescription = "Timne" });
            //data.Add(new DimLanguage() { DimLanguageId = 421, LanguageEdFactsCode = "ter", LanguageDescription = "Tereno" });
            //data.Add(new DimLanguage() { DimLanguageId = 422, LanguageEdFactsCode = "tet", LanguageDescription = "Tetum" });
            //data.Add(new DimLanguage() { DimLanguageId = 423, LanguageEdFactsCode = "tgk", LanguageDescription = "Tajik" });
            //data.Add(new DimLanguage() { DimLanguageId = 424, LanguageEdFactsCode = "tgl", LanguageDescription = "Tagalog" });
            //data.Add(new DimLanguage() { DimLanguageId = 425, LanguageEdFactsCode = "tha", LanguageDescription = "Thai" });
            //data.Add(new DimLanguage() { DimLanguageId = 426, LanguageEdFactsCode = "tib", LanguageDescription = "Tibetan" });
            //data.Add(new DimLanguage() { DimLanguageId = 427, LanguageEdFactsCode = "tig", LanguageDescription = "Tigre" });
            //data.Add(new DimLanguage() { DimLanguageId = 428, LanguageEdFactsCode = "tir", LanguageDescription = "Tigrinya" });
            //data.Add(new DimLanguage() { DimLanguageId = 429, LanguageEdFactsCode = "tiv", LanguageDescription = "Tiv" });
            //data.Add(new DimLanguage() { DimLanguageId = 430, LanguageEdFactsCode = "tkl", LanguageDescription = "Tokelau" });
            //data.Add(new DimLanguage() { DimLanguageId = 431, LanguageEdFactsCode = "tlh", LanguageDescription = "Klingon; tlhIngan-Hol" });
            //data.Add(new DimLanguage() { DimLanguageId = 432, LanguageEdFactsCode = "tli", LanguageDescription = "Tlingit" });
            //data.Add(new DimLanguage() { DimLanguageId = 433, LanguageEdFactsCode = "tmh", LanguageDescription = "Tamashek" });
            //data.Add(new DimLanguage() { DimLanguageId = 434, LanguageEdFactsCode = "tog", LanguageDescription = "Tonga (Nyasa)" });
            //data.Add(new DimLanguage() { DimLanguageId = 435, LanguageEdFactsCode = "ton", LanguageDescription = "Tonga (Tonga Islands)" });
            //data.Add(new DimLanguage() { DimLanguageId = 436, LanguageEdFactsCode = "tpi", LanguageDescription = "Tok Pisin" });
            //data.Add(new DimLanguage() { DimLanguageId = 437, LanguageEdFactsCode = "tsi", LanguageDescription = "Tsimshian" });
            //data.Add(new DimLanguage() { DimLanguageId = 438, LanguageEdFactsCode = "tsn", LanguageDescription = "Tswana" });
            //data.Add(new DimLanguage() { DimLanguageId = 439, LanguageEdFactsCode = "tso", LanguageDescription = "Tsonga" });
            //data.Add(new DimLanguage() { DimLanguageId = 440, LanguageEdFactsCode = "tuk", LanguageDescription = "Turkmen" });
            //data.Add(new DimLanguage() { DimLanguageId = 441, LanguageEdFactsCode = "tum", LanguageDescription = "Tumbuka" });
            //data.Add(new DimLanguage() { DimLanguageId = 442, LanguageEdFactsCode = "tup", LanguageDescription = "Tupi languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 443, LanguageEdFactsCode = "tur", LanguageDescription = "Turkish" });
            //data.Add(new DimLanguage() { DimLanguageId = 444, LanguageEdFactsCode = "tut", LanguageDescription = "Altaic languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 445, LanguageEdFactsCode = "tvl", LanguageDescription = "Tuvalu" });
            //data.Add(new DimLanguage() { DimLanguageId = 446, LanguageEdFactsCode = "twi", LanguageDescription = "Twi" });
            //data.Add(new DimLanguage() { DimLanguageId = 447, LanguageEdFactsCode = "tyv", LanguageDescription = "Tuvinian" });
            //data.Add(new DimLanguage() { DimLanguageId = 448, LanguageEdFactsCode = "udm", LanguageDescription = "Udmurt" });
            //data.Add(new DimLanguage() { DimLanguageId = 449, LanguageEdFactsCode = "uga", LanguageDescription = "Ugaritic" });
            //data.Add(new DimLanguage() { DimLanguageId = 450, LanguageEdFactsCode = "uig", LanguageDescription = "Uighur; Uyghur" });
            //data.Add(new DimLanguage() { DimLanguageId = 451, LanguageEdFactsCode = "ukr", LanguageDescription = "Ukrainian" });
            //data.Add(new DimLanguage() { DimLanguageId = 452, LanguageEdFactsCode = "umb", LanguageDescription = "Umbundu" });
            //data.Add(new DimLanguage() { DimLanguageId = 453, LanguageEdFactsCode = "und", LanguageDescription = "Undetermined" });
            //data.Add(new DimLanguage() { DimLanguageId = 454, LanguageEdFactsCode = "urd", LanguageDescription = "Urdu" });
            //data.Add(new DimLanguage() { DimLanguageId = 455, LanguageEdFactsCode = "uzb", LanguageDescription = "Uzbek" });
            //data.Add(new DimLanguage() { DimLanguageId = 456, LanguageEdFactsCode = "vai", LanguageDescription = "Vai" });
            //data.Add(new DimLanguage() { DimLanguageId = 457, LanguageEdFactsCode = "ven", LanguageDescription = "Venda" });
            //data.Add(new DimLanguage() { DimLanguageId = 458, LanguageEdFactsCode = "vie", LanguageDescription = "Vietnamese" });
            //data.Add(new DimLanguage() { DimLanguageId = 459, LanguageEdFactsCode = "vol", LanguageDescription = "Volap?k" });
            //data.Add(new DimLanguage() { DimLanguageId = 460, LanguageEdFactsCode = "vot", LanguageDescription = "Votic" });
            //data.Add(new DimLanguage() { DimLanguageId = 461, LanguageEdFactsCode = "wak", LanguageDescription = "Wakashan languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 462, LanguageEdFactsCode = "wal", LanguageDescription = "Wolaitta; Wolaytta" });
            //data.Add(new DimLanguage() { DimLanguageId = 463, LanguageEdFactsCode = "war", LanguageDescription = "Waray" });
            //data.Add(new DimLanguage() { DimLanguageId = 464, LanguageEdFactsCode = "was", LanguageDescription = "Washo" });
            //data.Add(new DimLanguage() { DimLanguageId = 465, LanguageEdFactsCode = "wel", LanguageDescription = "Welsh" });
            //data.Add(new DimLanguage() { DimLanguageId = 466, LanguageEdFactsCode = "wen", LanguageDescription = "Sorbian languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 467, LanguageEdFactsCode = "wln", LanguageDescription = "Walloon" });
            //data.Add(new DimLanguage() { DimLanguageId = 468, LanguageEdFactsCode = "wol", LanguageDescription = "Wolof" });
            //data.Add(new DimLanguage() { DimLanguageId = 469, LanguageEdFactsCode = "xal", LanguageDescription = "Kalmyk; Oirat" });
            //data.Add(new DimLanguage() { DimLanguageId = 470, LanguageEdFactsCode = "xho", LanguageDescription = "Xhosa" });
            //data.Add(new DimLanguage() { DimLanguageId = 471, LanguageEdFactsCode = "yao", LanguageDescription = "Yao" });
            //data.Add(new DimLanguage() { DimLanguageId = 472, LanguageEdFactsCode = "yap", LanguageDescription = "Yapese" });
            //data.Add(new DimLanguage() { DimLanguageId = 473, LanguageEdFactsCode = "yid", LanguageDescription = "Yiddish" });
            //data.Add(new DimLanguage() { DimLanguageId = 474, LanguageEdFactsCode = "yor", LanguageDescription = "Yoruba" });
            //data.Add(new DimLanguage() { DimLanguageId = 475, LanguageEdFactsCode = "ypk", LanguageDescription = "Yupik languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 476, LanguageEdFactsCode = "zap", LanguageDescription = "Zapotec" });
            //data.Add(new DimLanguage() { DimLanguageId = 477, LanguageEdFactsCode = "zbl", LanguageDescription = "Blissymbols; Blissymbolics; Bliss" });
            //data.Add(new DimLanguage() { DimLanguageId = 478, LanguageEdFactsCode = "zen", LanguageDescription = "Zenaga" });
            //data.Add(new DimLanguage() { DimLanguageId = 479, LanguageEdFactsCode = "zgh", LanguageDescription = "Standard Moroccan Tamazight" });
            //data.Add(new DimLanguage() { DimLanguageId = 480, LanguageEdFactsCode = "zha", LanguageDescription = "Zhuang; Chuang" });
            //data.Add(new DimLanguage() { DimLanguageId = 481, LanguageEdFactsCode = "znd", LanguageDescription = "Zande languages" });
            //data.Add(new DimLanguage() { DimLanguageId = 482, LanguageEdFactsCode = "zul", LanguageDescription = "Zulu" });
            //data.Add(new DimLanguage() { DimLanguageId = 483, LanguageEdFactsCode = "zun", LanguageDescription = "Zuni" });
            //data.Add(new DimLanguage() { DimLanguageId = 484, LanguageEdFactsCode = "zxx", LanguageDescription = "No linguistic content; Not applicable" });
            //data.Add(new DimLanguage() { DimLanguageId = 485, LanguageEdFactsCode = "zza", LanguageDescription = "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" });

            return data;

        }
    }
}
 