using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using generate.core.Models.RDS;

namespace generate.core.Helpers.ReferenceData
{
    public class DimOrganizationStatusHelper
    {
        public static List<DimK12OrganizationStatus> GetData()
        {


            var data = new List<DimK12OrganizationStatus>();

            /*
            select 'data.Add(new DimOrganizationStatus() { 
            DimOrganizationStatusId = ' + convert(varchar(20), DimOrganizationStatusId) + ',
            REAPAlternativeFundingStatusId = ' + convert(varchar(20), REAPAlternativeFundingStatusId) + ',
            REAPAlternativeFundingStatusEdFactsCode = "' + REAPAlternativeFundingStatusEdFactsCode + '",
            GunFreeStatusId = ' + convert(varchar(20), GunFreeStatusId) + ',
            GunFreeStatusEdFactsCode = "' + GunFreeStatusEdFactsCode + '",
            GraduationRateId = ' + convert(varchar(20), GraduationRateId) + ',
            GraduationRateEdFactsCode = "' + GraduationRateEdFactsCode + '",
			});'
            from rds.DimOrganizationStatus
            */
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = -1, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 1, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 2, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 3, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 4, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 5, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 6, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 7, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 8, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 9, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 10, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 11, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 12, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 13, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 14, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 15, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 16, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 17, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 18, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 19, REAPAlternativeFundingStatusId = -1, REAPAlternativeFundingStatusEdFactsCode = "MISSING", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 20, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 21, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 22, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 23, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 24, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 25, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 26, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 27, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 28, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 29, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 30, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 31, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 32, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 33, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 34, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 35, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 36, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 37, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 38, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 39, REAPAlternativeFundingStatusId = 1, REAPAlternativeFundingStatusEdFactsCode = "YES", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 40, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 41, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 42, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 43, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 44, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 45, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 46, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 47, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 48, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 49, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 50, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 51, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 52, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 53, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 54, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 55, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 56, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 57, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 58, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 59, REAPAlternativeFundingStatusId = 2, REAPAlternativeFundingStatusEdFactsCode = "NO", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 60, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 61, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 62, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 63, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = -1, GunFreeStatusEdFactsCode = "MISSING", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 64, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 65, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 66, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 67, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 1, GunFreeStatusEdFactsCode = "YESWITHREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 68, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 69, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 70, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 71, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 2, GunFreeStatusEdFactsCode = "YESWOREP", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 72, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 73, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 74, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 75, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 3, GunFreeStatusEdFactsCode = "NO", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 76, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = -1, GraduationRateEdFactsCode = "MISSING", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 77, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 1, GraduationRateEdFactsCode = "STTDEF", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 78, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 2, GraduationRateEdFactsCode = "TOOFEW", });
            //data.Add(new DimK12OrganizationStatus() { DimOrganizationStatusId = 79, REAPAlternativeFundingStatusId = 3, REAPAlternativeFundingStatusEdFactsCode = "NA", GunFreeStatusId = 4, GunFreeStatusEdFactsCode = "NA", GraduationRateId = 3, GraduationRateEdFactsCode = "NOSTUDENTS", });

            return data;

        }
    }
}
 