using generate.core.Models.IDS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace generate.core.Helpers.ReferenceData
{
    public static class RefLanguageHelper
    {

        public static List<RefLanguage> GetData()
        {
            /*
            select 'data.Add(new RefLanguage() { 
            RefLanguageId = ' + convert(varchar(20), RefLanguageId) + ',
            Code = "' + Code + '",
            Description = "' + [Description] + '"
            });'
            from dbo.RefLanguage
            */

            var data = new List<RefLanguage>();

            data.Add(new RefLanguage() { RefLanguageId = 1, Code = "aar", Description = "Afar" });
            data.Add(new RefLanguage() { RefLanguageId = 2, Code = "abk", Description = "Abkhazian" });
            data.Add(new RefLanguage() { RefLanguageId = 3, Code = "ace", Description = "Achinese" });
            data.Add(new RefLanguage() { RefLanguageId = 4, Code = "ach", Description = "Acoli" });
            data.Add(new RefLanguage() { RefLanguageId = 5, Code = "ada", Description = "Adangme" });
            data.Add(new RefLanguage() { RefLanguageId = 6, Code = "ady", Description = "Adyghe; Adygei" });
            data.Add(new RefLanguage() { RefLanguageId = 7, Code = "afa", Description = "Afro-Asiatic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 8, Code = "afh", Description = "Afrihili" });
            data.Add(new RefLanguage() { RefLanguageId = 9, Code = "afr", Description = "Afrikaans" });
            data.Add(new RefLanguage() { RefLanguageId = 10, Code = "ain", Description = "Ainu" });
            data.Add(new RefLanguage() { RefLanguageId = 11, Code = "aka", Description = "Akan" });
            data.Add(new RefLanguage() { RefLanguageId = 12, Code = "akk", Description = "Akkadian" });
            data.Add(new RefLanguage() { RefLanguageId = 13, Code = "alb", Description = "Albanian" });
            data.Add(new RefLanguage() { RefLanguageId = 14, Code = "ale", Description = "Aleut" });
            data.Add(new RefLanguage() { RefLanguageId = 15, Code = "alg", Description = "Algonquian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 16, Code = "alt", Description = "Southern Altai" });
            data.Add(new RefLanguage() { RefLanguageId = 17, Code = "amh", Description = "Amharic" });
            data.Add(new RefLanguage() { RefLanguageId = 18, Code = "ang", Description = "English, Old (ca.450-1100)" });
            data.Add(new RefLanguage() { RefLanguageId = 19, Code = "anp", Description = "Angika" });
            data.Add(new RefLanguage() { RefLanguageId = 20, Code = "apa", Description = "Apache languages" });
            data.Add(new RefLanguage() { RefLanguageId = 21, Code = "ara", Description = "Arabic" });
            data.Add(new RefLanguage() { RefLanguageId = 22, Code = "arc", Description = "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)" });
            data.Add(new RefLanguage() { RefLanguageId = 23, Code = "arg", Description = "Aragonese" });
            data.Add(new RefLanguage() { RefLanguageId = 24, Code = "arm", Description = "Armenian" });
            data.Add(new RefLanguage() { RefLanguageId = 25, Code = "arn", Description = "Mapudungun; Mapuche" });
            data.Add(new RefLanguage() { RefLanguageId = 26, Code = "arp", Description = "Arapaho" });
            data.Add(new RefLanguage() { RefLanguageId = 27, Code = "art", Description = "Artificial languages" });
            data.Add(new RefLanguage() { RefLanguageId = 28, Code = "arw", Description = "Arawak" });
            data.Add(new RefLanguage() { RefLanguageId = 29, Code = "asm", Description = "Assamese" });
            data.Add(new RefLanguage() { RefLanguageId = 30, Code = "ast", Description = "Asturian; Bable; Leonese; Asturleonese" });
            data.Add(new RefLanguage() { RefLanguageId = 31, Code = "ath", Description = "Athapascan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 32, Code = "aus", Description = "Australian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 33, Code = "ava", Description = "Avaric" });
            data.Add(new RefLanguage() { RefLanguageId = 34, Code = "ave", Description = "Avestan" });
            data.Add(new RefLanguage() { RefLanguageId = 35, Code = "awa", Description = "Awadhi" });
            data.Add(new RefLanguage() { RefLanguageId = 36, Code = "aym", Description = "Aymara" });
            data.Add(new RefLanguage() { RefLanguageId = 37, Code = "aze", Description = "Azerbaijani" });
            data.Add(new RefLanguage() { RefLanguageId = 38, Code = "bad", Description = "Banda languages" });
            data.Add(new RefLanguage() { RefLanguageId = 39, Code = "bai", Description = "Bamileke languages" });
            data.Add(new RefLanguage() { RefLanguageId = 40, Code = "bak", Description = "Bashkir" });
            data.Add(new RefLanguage() { RefLanguageId = 41, Code = "bal", Description = "Baluchi" });
            data.Add(new RefLanguage() { RefLanguageId = 42, Code = "bam", Description = "Bambara" });
            data.Add(new RefLanguage() { RefLanguageId = 43, Code = "ban", Description = "Balinese" });
            data.Add(new RefLanguage() { RefLanguageId = 44, Code = "baq", Description = "Basque" });
            data.Add(new RefLanguage() { RefLanguageId = 45, Code = "bas", Description = "Basa" });
            data.Add(new RefLanguage() { RefLanguageId = 46, Code = "bat", Description = "Baltic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 47, Code = "bej", Description = "Beja; Bedawiyet" });
            data.Add(new RefLanguage() { RefLanguageId = 48, Code = "bel", Description = "Belarusian" });
            data.Add(new RefLanguage() { RefLanguageId = 49, Code = "bem", Description = "Bemba" });
            data.Add(new RefLanguage() { RefLanguageId = 50, Code = "ben", Description = "Bengali" });
            data.Add(new RefLanguage() { RefLanguageId = 51, Code = "ber", Description = "Berber languages" });
            data.Add(new RefLanguage() { RefLanguageId = 52, Code = "bho", Description = "Bhojpuri" });
            data.Add(new RefLanguage() { RefLanguageId = 53, Code = "bih", Description = "Bihari languages" });
            data.Add(new RefLanguage() { RefLanguageId = 54, Code = "bik", Description = "Bikol" });
            data.Add(new RefLanguage() { RefLanguageId = 55, Code = "bin", Description = "Bini; Edo" });
            data.Add(new RefLanguage() { RefLanguageId = 56, Code = "bis", Description = "Bislama" });
            data.Add(new RefLanguage() { RefLanguageId = 57, Code = "bla", Description = "Siksika" });
            data.Add(new RefLanguage() { RefLanguageId = 58, Code = "bnt", Description = "Bantu languages" });
            data.Add(new RefLanguage() { RefLanguageId = 59, Code = "bos", Description = "Bosnian" });
            data.Add(new RefLanguage() { RefLanguageId = 60, Code = "bra", Description = "Braj" });
            data.Add(new RefLanguage() { RefLanguageId = 61, Code = "bre", Description = "Breton" });
            data.Add(new RefLanguage() { RefLanguageId = 62, Code = "btk", Description = "Batak languages" });
            data.Add(new RefLanguage() { RefLanguageId = 63, Code = "bua", Description = "Buriat" });
            data.Add(new RefLanguage() { RefLanguageId = 64, Code = "bug", Description = "Buginese" });
            data.Add(new RefLanguage() { RefLanguageId = 65, Code = "bul", Description = "Bulgarian" });
            data.Add(new RefLanguage() { RefLanguageId = 66, Code = "bur", Description = "Burmese" });
            data.Add(new RefLanguage() { RefLanguageId = 67, Code = "byn", Description = "Blin; Bilin" });
            data.Add(new RefLanguage() { RefLanguageId = 68, Code = "cad", Description = "Caddo" });
            data.Add(new RefLanguage() { RefLanguageId = 69, Code = "cai", Description = "Central American Indian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 70, Code = "car", Description = "Galibi Carib" });
            data.Add(new RefLanguage() { RefLanguageId = 71, Code = "cat", Description = "Catalan; Valencian" });
            data.Add(new RefLanguage() { RefLanguageId = 72, Code = "cau", Description = "Caucasian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 73, Code = "ceb", Description = "Cebuano" });
            data.Add(new RefLanguage() { RefLanguageId = 74, Code = "cel", Description = "Celtic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 75, Code = "cha", Description = "Chamorro" });
            data.Add(new RefLanguage() { RefLanguageId = 76, Code = "chb", Description = "Chibcha" });
            data.Add(new RefLanguage() { RefLanguageId = 77, Code = "che", Description = "Chechen" });
            data.Add(new RefLanguage() { RefLanguageId = 78, Code = "chg", Description = "Chagatai" });
            data.Add(new RefLanguage() { RefLanguageId = 79, Code = "chi", Description = "Chinese" });
            data.Add(new RefLanguage() { RefLanguageId = 80, Code = "chk", Description = "Chuukese" });
            data.Add(new RefLanguage() { RefLanguageId = 81, Code = "chm", Description = "Mari" });
            data.Add(new RefLanguage() { RefLanguageId = 82, Code = "chn", Description = "Chinook jargon" });
            data.Add(new RefLanguage() { RefLanguageId = 83, Code = "cho", Description = "Choctaw" });
            data.Add(new RefLanguage() { RefLanguageId = 84, Code = "chp", Description = "Chipewyan; Dene Suline" });
            data.Add(new RefLanguage() { RefLanguageId = 85, Code = "chr", Description = "Cherokee" });
            data.Add(new RefLanguage() { RefLanguageId = 86, Code = "chu", Description = "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" });
            data.Add(new RefLanguage() { RefLanguageId = 87, Code = "chv", Description = "Chuvash" });
            data.Add(new RefLanguage() { RefLanguageId = 88, Code = "chy", Description = "Cheyenne" });
            data.Add(new RefLanguage() { RefLanguageId = 89, Code = "cmc", Description = "Chamic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 90, Code = "cop", Description = "Coptic" });
            data.Add(new RefLanguage() { RefLanguageId = 91, Code = "cor", Description = "Cornish" });
            data.Add(new RefLanguage() { RefLanguageId = 92, Code = "cos", Description = "Corsican" });
            data.Add(new RefLanguage() { RefLanguageId = 93, Code = "cpe", Description = "Creoles and pidgins, English based" });
            data.Add(new RefLanguage() { RefLanguageId = 94, Code = "cpf", Description = "Creoles and pidgins, French-based" });
            data.Add(new RefLanguage() { RefLanguageId = 95, Code = "cpp", Description = "Creoles and pidgins, Portuguese-based" });
            data.Add(new RefLanguage() { RefLanguageId = 96, Code = "cre", Description = "Cree" });
            data.Add(new RefLanguage() { RefLanguageId = 97, Code = "crh", Description = "Crimean Tatar; Crimean Turkish" });
            data.Add(new RefLanguage() { RefLanguageId = 98, Code = "crp", Description = "Creoles and pidgins " });
            data.Add(new RefLanguage() { RefLanguageId = 99, Code = "csb", Description = "Kashubian" });
            data.Add(new RefLanguage() { RefLanguageId = 100, Code = "cus", Description = "Cushitic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 101, Code = "cze", Description = "Czech" });
            data.Add(new RefLanguage() { RefLanguageId = 102, Code = "dak", Description = "Dakota" });
            data.Add(new RefLanguage() { RefLanguageId = 103, Code = "dan", Description = "Danish" });
            data.Add(new RefLanguage() { RefLanguageId = 104, Code = "dar", Description = "Dargwa" });
            data.Add(new RefLanguage() { RefLanguageId = 105, Code = "day", Description = "Land Dayak languages" });
            data.Add(new RefLanguage() { RefLanguageId = 106, Code = "del", Description = "Delaware" });
            data.Add(new RefLanguage() { RefLanguageId = 107, Code = "den", Description = "Slave (Athapascan)" });
            data.Add(new RefLanguage() { RefLanguageId = 108, Code = "dgr", Description = "Dogrib" });
            data.Add(new RefLanguage() { RefLanguageId = 109, Code = "din", Description = "Dinka" });
            data.Add(new RefLanguage() { RefLanguageId = 110, Code = "div", Description = "Divehi; Dhivehi; Maldivian" });
            data.Add(new RefLanguage() { RefLanguageId = 111, Code = "doi", Description = "Dogri" });
            data.Add(new RefLanguage() { RefLanguageId = 112, Code = "dra", Description = "Dravidian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 113, Code = "dsb", Description = "Lower Sorbian" });
            data.Add(new RefLanguage() { RefLanguageId = 114, Code = "dua", Description = "Duala" });
            data.Add(new RefLanguage() { RefLanguageId = 115, Code = "dum", Description = "Dutch, Middle (ca.1050-1350)" });
            data.Add(new RefLanguage() { RefLanguageId = 116, Code = "dut", Description = "Dutch; Flemish" });
            data.Add(new RefLanguage() { RefLanguageId = 117, Code = "dyu", Description = "Dyula" });
            data.Add(new RefLanguage() { RefLanguageId = 118, Code = "dzo", Description = "Dzongkha" });
            data.Add(new RefLanguage() { RefLanguageId = 119, Code = "efi", Description = "Efik" });
            data.Add(new RefLanguage() { RefLanguageId = 120, Code = "egy", Description = "Egyptian (Ancient)" });
            data.Add(new RefLanguage() { RefLanguageId = 121, Code = "eka", Description = "Ekajuk" });
            data.Add(new RefLanguage() { RefLanguageId = 122, Code = "elx", Description = "Elamite" });
            data.Add(new RefLanguage() { RefLanguageId = 123, Code = "eng", Description = "English" });
            data.Add(new RefLanguage() { RefLanguageId = 124, Code = "enm", Description = "English, Middle (1100-1500)" });
            data.Add(new RefLanguage() { RefLanguageId = 125, Code = "epo", Description = "Esperanto" });
            data.Add(new RefLanguage() { RefLanguageId = 126, Code = "est", Description = "Estonian" });
            data.Add(new RefLanguage() { RefLanguageId = 127, Code = "ewe", Description = "Ewe" });
            data.Add(new RefLanguage() { RefLanguageId = 128, Code = "ewo", Description = "Ewondo" });
            data.Add(new RefLanguage() { RefLanguageId = 129, Code = "fan", Description = "Fang" });
            data.Add(new RefLanguage() { RefLanguageId = 130, Code = "fao", Description = "Faroese" });
            data.Add(new RefLanguage() { RefLanguageId = 131, Code = "fat", Description = "Fanti" });
            data.Add(new RefLanguage() { RefLanguageId = 132, Code = "fij", Description = "Fijian" });
            data.Add(new RefLanguage() { RefLanguageId = 133, Code = "fil", Description = "Filipino; Pilipino" });
            data.Add(new RefLanguage() { RefLanguageId = 134, Code = "fin", Description = "Finnish" });
            data.Add(new RefLanguage() { RefLanguageId = 135, Code = "fiu", Description = "Finno-Ugrian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 136, Code = "fon", Description = "Fon" });
            data.Add(new RefLanguage() { RefLanguageId = 137, Code = "fre", Description = "French" });
            data.Add(new RefLanguage() { RefLanguageId = 138, Code = "frm", Description = "French, Middle (ca.1400-1600)" });
            data.Add(new RefLanguage() { RefLanguageId = 139, Code = "fro", Description = "French, Old (842-ca.1400)" });
            data.Add(new RefLanguage() { RefLanguageId = 140, Code = "frr", Description = "Northern Frisian" });
            data.Add(new RefLanguage() { RefLanguageId = 141, Code = "frs", Description = "Eastern Frisian" });
            data.Add(new RefLanguage() { RefLanguageId = 142, Code = "fry", Description = "Western Frisian" });
            data.Add(new RefLanguage() { RefLanguageId = 143, Code = "ful", Description = "Fulah" });
            data.Add(new RefLanguage() { RefLanguageId = 144, Code = "fur", Description = "Friulian" });
            data.Add(new RefLanguage() { RefLanguageId = 145, Code = "gaa", Description = "Ga" });
            data.Add(new RefLanguage() { RefLanguageId = 146, Code = "gay", Description = "Gayo" });
            data.Add(new RefLanguage() { RefLanguageId = 147, Code = "gba", Description = "Gbaya" });
            data.Add(new RefLanguage() { RefLanguageId = 148, Code = "gem", Description = "Germanic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 149, Code = "geo", Description = "Georgian" });
            data.Add(new RefLanguage() { RefLanguageId = 150, Code = "ger", Description = "German" });
            data.Add(new RefLanguage() { RefLanguageId = 151, Code = "gez", Description = "Geez" });
            data.Add(new RefLanguage() { RefLanguageId = 152, Code = "gil", Description = "Gilbertese" });
            data.Add(new RefLanguage() { RefLanguageId = 153, Code = "gla", Description = "Gaelic; Scottish Gaelic" });
            data.Add(new RefLanguage() { RefLanguageId = 154, Code = "gle", Description = "Irish" });
            data.Add(new RefLanguage() { RefLanguageId = 155, Code = "glg", Description = "Galician" });
            data.Add(new RefLanguage() { RefLanguageId = 156, Code = "glv", Description = "Manx" });
            data.Add(new RefLanguage() { RefLanguageId = 157, Code = "gmh", Description = "German, Middle High (ca.1050-1500)" });
            data.Add(new RefLanguage() { RefLanguageId = 158, Code = "goh", Description = "German, Old High (ca.750-1050)" });
            data.Add(new RefLanguage() { RefLanguageId = 159, Code = "gon", Description = "Gondi" });
            data.Add(new RefLanguage() { RefLanguageId = 160, Code = "gor", Description = "Gorontalo" });
            data.Add(new RefLanguage() { RefLanguageId = 161, Code = "got", Description = "Gothic" });
            data.Add(new RefLanguage() { RefLanguageId = 162, Code = "grb", Description = "Grebo" });
            data.Add(new RefLanguage() { RefLanguageId = 163, Code = "grc", Description = "Greek, Ancient (to 1453)" });
            data.Add(new RefLanguage() { RefLanguageId = 164, Code = "gre", Description = "Greek, Modern (1453-)" });
            data.Add(new RefLanguage() { RefLanguageId = 165, Code = "grn", Description = "Guarani" });
            data.Add(new RefLanguage() { RefLanguageId = 166, Code = "gsw", Description = "Swiss German; Alemannic; Alsatian" });
            data.Add(new RefLanguage() { RefLanguageId = 167, Code = "guj", Description = "Gujarati" });
            data.Add(new RefLanguage() { RefLanguageId = 168, Code = "gwi", Description = "Gwich'in" });
            data.Add(new RefLanguage() { RefLanguageId = 169, Code = "hai", Description = "Haida" });
            data.Add(new RefLanguage() { RefLanguageId = 170, Code = "hat", Description = "Haitian; Haitian Creole" });
            data.Add(new RefLanguage() { RefLanguageId = 171, Code = "hau", Description = "Hausa" });
            data.Add(new RefLanguage() { RefLanguageId = 172, Code = "haw", Description = "Hawaiian" });
            data.Add(new RefLanguage() { RefLanguageId = 173, Code = "heb", Description = "Hebrew" });
            data.Add(new RefLanguage() { RefLanguageId = 174, Code = "her", Description = "Herero" });
            data.Add(new RefLanguage() { RefLanguageId = 175, Code = "hil", Description = "Hiligaynon" });
            data.Add(new RefLanguage() { RefLanguageId = 176, Code = "him", Description = "Himachali languages; Western Pahari languages" });
            data.Add(new RefLanguage() { RefLanguageId = 177, Code = "hin", Description = "Hindi" });
            data.Add(new RefLanguage() { RefLanguageId = 178, Code = "hit", Description = "Hittite" });
            data.Add(new RefLanguage() { RefLanguageId = 179, Code = "hmn", Description = "Hmong; Mong" });
            data.Add(new RefLanguage() { RefLanguageId = 180, Code = "hmo", Description = "Hiri Motu" });
            data.Add(new RefLanguage() { RefLanguageId = 181, Code = "hrv", Description = "Croatian" });
            data.Add(new RefLanguage() { RefLanguageId = 182, Code = "hsb", Description = "Upper Sorbian" });
            data.Add(new RefLanguage() { RefLanguageId = 183, Code = "hun", Description = "Hungarian" });
            data.Add(new RefLanguage() { RefLanguageId = 184, Code = "hup", Description = "Hupa" });
            data.Add(new RefLanguage() { RefLanguageId = 185, Code = "iba", Description = "Iban" });
            data.Add(new RefLanguage() { RefLanguageId = 186, Code = "ibo", Description = "Igbo" });
            data.Add(new RefLanguage() { RefLanguageId = 187, Code = "ice", Description = "Icelandic" });
            data.Add(new RefLanguage() { RefLanguageId = 188, Code = "ido", Description = "Ido" });
            data.Add(new RefLanguage() { RefLanguageId = 189, Code = "iii", Description = "Sichuan Yi; Nuosu" });
            data.Add(new RefLanguage() { RefLanguageId = 190, Code = "ijo", Description = "Ijo languages" });
            data.Add(new RefLanguage() { RefLanguageId = 191, Code = "iku", Description = "Inuktitut" });
            data.Add(new RefLanguage() { RefLanguageId = 192, Code = "ile", Description = "Interlingue; Occidental" });
            data.Add(new RefLanguage() { RefLanguageId = 193, Code = "ilo", Description = "Iloko" });
            data.Add(new RefLanguage() { RefLanguageId = 194, Code = "ina", Description = "Interlingua (International Auxiliary Language Association)" });
            data.Add(new RefLanguage() { RefLanguageId = 195, Code = "inc", Description = "Indic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 196, Code = "ind", Description = "Indonesian" });
            data.Add(new RefLanguage() { RefLanguageId = 197, Code = "ine", Description = "Indo-European languages" });
            data.Add(new RefLanguage() { RefLanguageId = 198, Code = "inh", Description = "Ingush" });
            data.Add(new RefLanguage() { RefLanguageId = 199, Code = "ipk", Description = "Inupiaq" });
            data.Add(new RefLanguage() { RefLanguageId = 200, Code = "ira", Description = "Iranian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 201, Code = "iro", Description = "Iroquoian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 202, Code = "ita", Description = "Italian" });
            data.Add(new RefLanguage() { RefLanguageId = 203, Code = "jav", Description = "Javanese" });
            data.Add(new RefLanguage() { RefLanguageId = 204, Code = "jbo", Description = "Lojban" });
            data.Add(new RefLanguage() { RefLanguageId = 205, Code = "jpn", Description = "Japanese" });
            data.Add(new RefLanguage() { RefLanguageId = 206, Code = "jpr", Description = "Judeo-Persian" });
            data.Add(new RefLanguage() { RefLanguageId = 207, Code = "jrb", Description = "Judeo-Arabic" });
            data.Add(new RefLanguage() { RefLanguageId = 208, Code = "kaa", Description = "Kara-Kalpak" });
            data.Add(new RefLanguage() { RefLanguageId = 209, Code = "kab", Description = "Kabyle" });
            data.Add(new RefLanguage() { RefLanguageId = 210, Code = "kac", Description = "Kachin; Jingpho" });
            data.Add(new RefLanguage() { RefLanguageId = 211, Code = "kal", Description = "Kalaallisut; Greenlandic" });
            data.Add(new RefLanguage() { RefLanguageId = 212, Code = "kam", Description = "Kamba" });
            data.Add(new RefLanguage() { RefLanguageId = 213, Code = "kan", Description = "Kannada" });
            data.Add(new RefLanguage() { RefLanguageId = 214, Code = "kar", Description = "Karen languages" });
            data.Add(new RefLanguage() { RefLanguageId = 215, Code = "kas", Description = "Kashmiri" });
            data.Add(new RefLanguage() { RefLanguageId = 216, Code = "kau", Description = "Kanuri" });
            data.Add(new RefLanguage() { RefLanguageId = 217, Code = "kaw", Description = "Kawi" });
            data.Add(new RefLanguage() { RefLanguageId = 218, Code = "kaz", Description = "Kazakh" });
            data.Add(new RefLanguage() { RefLanguageId = 219, Code = "kbd", Description = "Kabardian" });
            data.Add(new RefLanguage() { RefLanguageId = 220, Code = "kha", Description = "Khasi" });
            data.Add(new RefLanguage() { RefLanguageId = 221, Code = "khi", Description = "Khoisan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 222, Code = "khm", Description = "Central Khmer" });
            data.Add(new RefLanguage() { RefLanguageId = 223, Code = "kho", Description = "Khotanese; Sakan" });
            data.Add(new RefLanguage() { RefLanguageId = 224, Code = "kik", Description = "Kikuyu; Gikuyu" });
            data.Add(new RefLanguage() { RefLanguageId = 225, Code = "kin", Description = "Kinyarwanda" });
            data.Add(new RefLanguage() { RefLanguageId = 226, Code = "kir", Description = "Kirghiz; Kyrgyz" });
            data.Add(new RefLanguage() { RefLanguageId = 227, Code = "kmb", Description = "Kimbundu" });
            data.Add(new RefLanguage() { RefLanguageId = 228, Code = "kok", Description = "Konkani" });
            data.Add(new RefLanguage() { RefLanguageId = 229, Code = "kom", Description = "Komi" });
            data.Add(new RefLanguage() { RefLanguageId = 230, Code = "kon", Description = "Kongo" });
            data.Add(new RefLanguage() { RefLanguageId = 231, Code = "kor", Description = "Korean" });
            data.Add(new RefLanguage() { RefLanguageId = 232, Code = "kos", Description = "Kosraean" });
            data.Add(new RefLanguage() { RefLanguageId = 233, Code = "kpe", Description = "Kpelle" });
            data.Add(new RefLanguage() { RefLanguageId = 234, Code = "krc", Description = "Karachay-Balkar" });
            data.Add(new RefLanguage() { RefLanguageId = 235, Code = "krl", Description = "Karelian" });
            data.Add(new RefLanguage() { RefLanguageId = 236, Code = "kro", Description = "Kru languages" });
            data.Add(new RefLanguage() { RefLanguageId = 237, Code = "kru", Description = "Kurukh" });
            data.Add(new RefLanguage() { RefLanguageId = 238, Code = "kua", Description = "Kuanyama; Kwanyama" });
            data.Add(new RefLanguage() { RefLanguageId = 239, Code = "kum", Description = "Kumyk" });
            data.Add(new RefLanguage() { RefLanguageId = 240, Code = "kur", Description = "Kurdish" });
            data.Add(new RefLanguage() { RefLanguageId = 241, Code = "kut", Description = "Kutenai" });
            data.Add(new RefLanguage() { RefLanguageId = 242, Code = "lad", Description = "Ladino" });
            data.Add(new RefLanguage() { RefLanguageId = 243, Code = "lah", Description = "Lahnda" });
            data.Add(new RefLanguage() { RefLanguageId = 244, Code = "lam", Description = "Lamba" });
            data.Add(new RefLanguage() { RefLanguageId = 245, Code = "lao", Description = "Lao" });
            data.Add(new RefLanguage() { RefLanguageId = 246, Code = "lat", Description = "Latin" });
            data.Add(new RefLanguage() { RefLanguageId = 247, Code = "lav", Description = "Latvian" });
            data.Add(new RefLanguage() { RefLanguageId = 248, Code = "lez", Description = "Lezghian" });
            data.Add(new RefLanguage() { RefLanguageId = 249, Code = "lim", Description = "Limburgan; Limburger; Limburgish" });
            data.Add(new RefLanguage() { RefLanguageId = 250, Code = "lin", Description = "Lingala" });
            data.Add(new RefLanguage() { RefLanguageId = 251, Code = "lit", Description = "Lithuanian" });
            data.Add(new RefLanguage() { RefLanguageId = 252, Code = "lol", Description = "Mongo" });
            data.Add(new RefLanguage() { RefLanguageId = 253, Code = "loz", Description = "Lozi" });
            data.Add(new RefLanguage() { RefLanguageId = 254, Code = "ltz", Description = "Luxembourgish; Letzeburgesch" });
            data.Add(new RefLanguage() { RefLanguageId = 255, Code = "lua", Description = "Luba-Lulua" });
            data.Add(new RefLanguage() { RefLanguageId = 256, Code = "lub", Description = "Luba-Katanga" });
            data.Add(new RefLanguage() { RefLanguageId = 257, Code = "lug", Description = "Ganda" });
            data.Add(new RefLanguage() { RefLanguageId = 258, Code = "lui", Description = "Luiseno" });
            data.Add(new RefLanguage() { RefLanguageId = 259, Code = "lun", Description = "Lunda" });
            data.Add(new RefLanguage() { RefLanguageId = 260, Code = "luo", Description = "Luo (Kenya and Tanzania)" });
            data.Add(new RefLanguage() { RefLanguageId = 261, Code = "lus", Description = "Lushai" });
            data.Add(new RefLanguage() { RefLanguageId = 262, Code = "mac", Description = "Macedonian" });
            data.Add(new RefLanguage() { RefLanguageId = 263, Code = "mad", Description = "Madurese" });
            data.Add(new RefLanguage() { RefLanguageId = 264, Code = "mag", Description = "Magahi" });
            data.Add(new RefLanguage() { RefLanguageId = 265, Code = "mah", Description = "Marshallese" });
            data.Add(new RefLanguage() { RefLanguageId = 266, Code = "mai", Description = "Maithili" });
            data.Add(new RefLanguage() { RefLanguageId = 267, Code = "mak", Description = "Makasar" });
            data.Add(new RefLanguage() { RefLanguageId = 268, Code = "mal", Description = "Malayalam" });
            data.Add(new RefLanguage() { RefLanguageId = 269, Code = "man", Description = "Mandingo" });
            data.Add(new RefLanguage() { RefLanguageId = 270, Code = "mao", Description = "Maori" });
            data.Add(new RefLanguage() { RefLanguageId = 271, Code = "map", Description = "Austronesian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 272, Code = "mar", Description = "Marathi" });
            data.Add(new RefLanguage() { RefLanguageId = 273, Code = "mas", Description = "Masai" });
            data.Add(new RefLanguage() { RefLanguageId = 274, Code = "may", Description = "Malay" });
            data.Add(new RefLanguage() { RefLanguageId = 275, Code = "mdf", Description = "Moksha" });
            data.Add(new RefLanguage() { RefLanguageId = 276, Code = "mdr", Description = "Mandar" });
            data.Add(new RefLanguage() { RefLanguageId = 277, Code = "men", Description = "Mende" });
            data.Add(new RefLanguage() { RefLanguageId = 278, Code = "mga", Description = "Irish, Middle (900-1200)" });
            data.Add(new RefLanguage() { RefLanguageId = 279, Code = "mic", Description = "Mi'kmaq; Micmac" });
            data.Add(new RefLanguage() { RefLanguageId = 280, Code = "min", Description = "Minangkabau" });
            data.Add(new RefLanguage() { RefLanguageId = 281, Code = "mis", Description = "Uncoded languages" });
            data.Add(new RefLanguage() { RefLanguageId = 282, Code = "mkh", Description = "Mon-Khmer languages" });
            data.Add(new RefLanguage() { RefLanguageId = 283, Code = "mlg", Description = "Malagasy" });
            data.Add(new RefLanguage() { RefLanguageId = 284, Code = "mlt", Description = "Maltese" });
            data.Add(new RefLanguage() { RefLanguageId = 285, Code = "mnc", Description = "Manchu" });
            data.Add(new RefLanguage() { RefLanguageId = 286, Code = "mni", Description = "Manipuri" });
            data.Add(new RefLanguage() { RefLanguageId = 287, Code = "mno", Description = "Manobo languages" });
            data.Add(new RefLanguage() { RefLanguageId = 288, Code = "moh", Description = "Mohawk" });
            data.Add(new RefLanguage() { RefLanguageId = 289, Code = "mon", Description = "Mongolian" });
            data.Add(new RefLanguage() { RefLanguageId = 290, Code = "mos", Description = "Mossi" });
            data.Add(new RefLanguage() { RefLanguageId = 291, Code = "mul", Description = "Multiple languages" });
            data.Add(new RefLanguage() { RefLanguageId = 292, Code = "mun", Description = "Munda languages" });
            data.Add(new RefLanguage() { RefLanguageId = 293, Code = "mus", Description = "Creek" });
            data.Add(new RefLanguage() { RefLanguageId = 294, Code = "mwl", Description = "Mirandese" });
            data.Add(new RefLanguage() { RefLanguageId = 295, Code = "mwr", Description = "Marwari" });
            data.Add(new RefLanguage() { RefLanguageId = 296, Code = "myn", Description = "Mayan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 297, Code = "myv", Description = "Erzya" });
            data.Add(new RefLanguage() { RefLanguageId = 298, Code = "nah", Description = "Nahuatl languages" });
            data.Add(new RefLanguage() { RefLanguageId = 299, Code = "nai", Description = "North American Indian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 300, Code = "nap", Description = "Neapolitan" });
            data.Add(new RefLanguage() { RefLanguageId = 301, Code = "nau", Description = "Nauru" });
            data.Add(new RefLanguage() { RefLanguageId = 302, Code = "nav", Description = "Navajo; Navaho" });
            data.Add(new RefLanguage() { RefLanguageId = 303, Code = "nbl", Description = "Ndebele, South; South Ndebele" });
            data.Add(new RefLanguage() { RefLanguageId = 304, Code = "nde", Description = "Ndebele, North; North Ndebele" });
            data.Add(new RefLanguage() { RefLanguageId = 305, Code = "ndo", Description = "Ndonga" });
            data.Add(new RefLanguage() { RefLanguageId = 306, Code = "nds", Description = "Low German; Low Saxon; German, Low; Saxon, Low" });
            data.Add(new RefLanguage() { RefLanguageId = 307, Code = "nep", Description = "Nepali" });
            data.Add(new RefLanguage() { RefLanguageId = 308, Code = "new", Description = "Nepal Bhasa; Newari" });
            data.Add(new RefLanguage() { RefLanguageId = 309, Code = "nia", Description = "Nias" });
            data.Add(new RefLanguage() { RefLanguageId = 310, Code = "nic", Description = "Niger-Kordofanian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 311, Code = "niu", Description = "Niuean" });
            data.Add(new RefLanguage() { RefLanguageId = 312, Code = "nno", Description = "Norwegian Nynorsk; Nynorsk, Norwegian" });
            data.Add(new RefLanguage() { RefLanguageId = 313, Code = "nob", Description = "Bokm?l, Norwegian; Norwegian Bokm?l" });
            data.Add(new RefLanguage() { RefLanguageId = 314, Code = "nog", Description = "Nogai" });
            data.Add(new RefLanguage() { RefLanguageId = 315, Code = "non", Description = "Norse, Old" });
            data.Add(new RefLanguage() { RefLanguageId = 316, Code = "nor", Description = "Norwegian" });
            data.Add(new RefLanguage() { RefLanguageId = 317, Code = "nqo", Description = "N'Ko" });
            data.Add(new RefLanguage() { RefLanguageId = 318, Code = "nso", Description = "Pedi; Sepedi; Northern Sotho" });
            data.Add(new RefLanguage() { RefLanguageId = 319, Code = "nub", Description = "Nubian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 320, Code = "nwc", Description = "Classical Newari; Old Newari; Classical Nepal Bhasa" });
            data.Add(new RefLanguage() { RefLanguageId = 321, Code = "nya", Description = "Chichewa; Chewa; Nyanja" });
            data.Add(new RefLanguage() { RefLanguageId = 322, Code = "nym", Description = "Nyamwezi" });
            data.Add(new RefLanguage() { RefLanguageId = 323, Code = "nyn", Description = "Nyankole" });
            data.Add(new RefLanguage() { RefLanguageId = 324, Code = "nyo", Description = "Nyoro" });
            data.Add(new RefLanguage() { RefLanguageId = 325, Code = "nzi", Description = "Nzima" });
            data.Add(new RefLanguage() { RefLanguageId = 326, Code = "oci", Description = "Occitan (post 1500)" });
            data.Add(new RefLanguage() { RefLanguageId = 327, Code = "oji", Description = "Ojibwa" });
            data.Add(new RefLanguage() { RefLanguageId = 328, Code = "ori", Description = "Oriya" });
            data.Add(new RefLanguage() { RefLanguageId = 329, Code = "orm", Description = "Oromo" });
            data.Add(new RefLanguage() { RefLanguageId = 330, Code = "osa", Description = "Osage" });
            data.Add(new RefLanguage() { RefLanguageId = 331, Code = "oss", Description = "Ossetian; Ossetic" });
            data.Add(new RefLanguage() { RefLanguageId = 332, Code = "ota", Description = "Turkish, Ottoman (1500-1928)" });
            data.Add(new RefLanguage() { RefLanguageId = 333, Code = "oto", Description = "Otomian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 334, Code = "paa", Description = "Papuan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 335, Code = "pag", Description = "Pangasinan" });
            data.Add(new RefLanguage() { RefLanguageId = 336, Code = "pal", Description = "Pahlavi" });
            data.Add(new RefLanguage() { RefLanguageId = 337, Code = "pam", Description = "Pampanga; Kapampangan" });
            data.Add(new RefLanguage() { RefLanguageId = 338, Code = "pan", Description = "Panjabi; Punjabi" });
            data.Add(new RefLanguage() { RefLanguageId = 339, Code = "pap", Description = "Papiamento" });
            data.Add(new RefLanguage() { RefLanguageId = 340, Code = "pau", Description = "Palauan" });
            data.Add(new RefLanguage() { RefLanguageId = 341, Code = "peo", Description = "Persian, Old (ca.600-400 B.C.)" });
            data.Add(new RefLanguage() { RefLanguageId = 342, Code = "per", Description = "Persian" });
            data.Add(new RefLanguage() { RefLanguageId = 343, Code = "phi", Description = "Philippine languages" });
            data.Add(new RefLanguage() { RefLanguageId = 344, Code = "phn", Description = "Phoenician" });
            data.Add(new RefLanguage() { RefLanguageId = 345, Code = "pli", Description = "Pali" });
            data.Add(new RefLanguage() { RefLanguageId = 346, Code = "pol", Description = "Polish" });
            data.Add(new RefLanguage() { RefLanguageId = 347, Code = "pon", Description = "Pohnpeian" });
            data.Add(new RefLanguage() { RefLanguageId = 348, Code = "por", Description = "Portuguese" });
            data.Add(new RefLanguage() { RefLanguageId = 349, Code = "pra", Description = "Prakrit languages" });
            data.Add(new RefLanguage() { RefLanguageId = 350, Code = "pro", Description = "Proven?al, Old (to 1500); Occitan, Old (to 1500)" });
            data.Add(new RefLanguage() { RefLanguageId = 351, Code = "pus", Description = "Pushto; Pashto" });
            data.Add(new RefLanguage() { RefLanguageId = 352, Code = "que", Description = "Quechua" });
            data.Add(new RefLanguage() { RefLanguageId = 353, Code = "raj", Description = "Rajasthani" });
            data.Add(new RefLanguage() { RefLanguageId = 354, Code = "rap", Description = "Rapanui" });
            data.Add(new RefLanguage() { RefLanguageId = 355, Code = "rar", Description = "Rarotongan; Cook Islands Maori" });
            data.Add(new RefLanguage() { RefLanguageId = 356, Code = "roa", Description = "Romance languages" });
            data.Add(new RefLanguage() { RefLanguageId = 357, Code = "roh", Description = "Romansh" });
            data.Add(new RefLanguage() { RefLanguageId = 358, Code = "rom", Description = "Romany" });
            data.Add(new RefLanguage() { RefLanguageId = 359, Code = "rum", Description = "Romanian" });
            data.Add(new RefLanguage() { RefLanguageId = 360, Code = "run", Description = "Rundi" });
            data.Add(new RefLanguage() { RefLanguageId = 361, Code = "rup", Description = "Aromanian; Arumanian; Macedo-Romanian" });
            data.Add(new RefLanguage() { RefLanguageId = 362, Code = "rus", Description = "Russian" });
            data.Add(new RefLanguage() { RefLanguageId = 363, Code = "sad", Description = "Sandawe" });
            data.Add(new RefLanguage() { RefLanguageId = 364, Code = "sag", Description = "Sango" });
            data.Add(new RefLanguage() { RefLanguageId = 365, Code = "sah", Description = "Yakut" });
            data.Add(new RefLanguage() { RefLanguageId = 366, Code = "sai", Description = "South American Indian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 367, Code = "sal", Description = "Salishan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 368, Code = "sam", Description = "Samaritan Aramaic" });
            data.Add(new RefLanguage() { RefLanguageId = 369, Code = "san", Description = "Sanskrit" });
            data.Add(new RefLanguage() { RefLanguageId = 370, Code = "sas", Description = "Sasak" });
            data.Add(new RefLanguage() { RefLanguageId = 371, Code = "sat", Description = "Santali" });
            data.Add(new RefLanguage() { RefLanguageId = 372, Code = "scn", Description = "Sicilian" });
            data.Add(new RefLanguage() { RefLanguageId = 373, Code = "sco", Description = "Scots" });
            data.Add(new RefLanguage() { RefLanguageId = 374, Code = "sel", Description = "Selkup" });
            data.Add(new RefLanguage() { RefLanguageId = 375, Code = "sem", Description = "Semitic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 376, Code = "sga", Description = "Irish, Old (to 900)" });
            data.Add(new RefLanguage() { RefLanguageId = 377, Code = "sgn", Description = "Sign Languages" });
            data.Add(new RefLanguage() { RefLanguageId = 378, Code = "shn", Description = "Shan" });
            data.Add(new RefLanguage() { RefLanguageId = 379, Code = "sid", Description = "Sidamo" });
            data.Add(new RefLanguage() { RefLanguageId = 380, Code = "sin", Description = "Sinhala; Sinhalese" });
            data.Add(new RefLanguage() { RefLanguageId = 381, Code = "sio", Description = "Siouan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 382, Code = "sit", Description = "Sino-Tibetan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 383, Code = "sla", Description = "Slavic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 384, Code = "slo", Description = "Slovak" });
            data.Add(new RefLanguage() { RefLanguageId = 385, Code = "slv", Description = "Slovenian" });
            data.Add(new RefLanguage() { RefLanguageId = 386, Code = "sma", Description = "Southern Sami" });
            data.Add(new RefLanguage() { RefLanguageId = 387, Code = "sme", Description = "Northern Sami" });
            data.Add(new RefLanguage() { RefLanguageId = 388, Code = "smi", Description = "Sami languages" });
            data.Add(new RefLanguage() { RefLanguageId = 389, Code = "smj", Description = "Lule Sami" });
            data.Add(new RefLanguage() { RefLanguageId = 390, Code = "smn", Description = "Inari Sami" });
            data.Add(new RefLanguage() { RefLanguageId = 391, Code = "smo", Description = "Samoan" });
            data.Add(new RefLanguage() { RefLanguageId = 392, Code = "sms", Description = "Skolt Sami" });
            data.Add(new RefLanguage() { RefLanguageId = 393, Code = "sna", Description = "Shona" });
            data.Add(new RefLanguage() { RefLanguageId = 394, Code = "snd", Description = "Sindhi" });
            data.Add(new RefLanguage() { RefLanguageId = 395, Code = "snk", Description = "Soninke" });
            data.Add(new RefLanguage() { RefLanguageId = 396, Code = "sog", Description = "Sogdian" });
            data.Add(new RefLanguage() { RefLanguageId = 397, Code = "som", Description = "Somali" });
            data.Add(new RefLanguage() { RefLanguageId = 398, Code = "son", Description = "Songhai languages" });
            data.Add(new RefLanguage() { RefLanguageId = 399, Code = "sot", Description = "Sotho, Southern" });
            data.Add(new RefLanguage() { RefLanguageId = 400, Code = "spa", Description = "Spanish; Castilian" });
            data.Add(new RefLanguage() { RefLanguageId = 401, Code = "srd", Description = "Sardinian" });
            data.Add(new RefLanguage() { RefLanguageId = 402, Code = "srn", Description = "Sranan Tongo" });
            data.Add(new RefLanguage() { RefLanguageId = 403, Code = "srp", Description = "Serbian" });
            data.Add(new RefLanguage() { RefLanguageId = 404, Code = "srr", Description = "Serer" });
            data.Add(new RefLanguage() { RefLanguageId = 405, Code = "ssa", Description = "Nilo-Saharan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 406, Code = "ssw", Description = "Swati" });
            data.Add(new RefLanguage() { RefLanguageId = 407, Code = "suk", Description = "Sukuma" });
            data.Add(new RefLanguage() { RefLanguageId = 408, Code = "sun", Description = "Sundanese" });
            data.Add(new RefLanguage() { RefLanguageId = 409, Code = "sus", Description = "Susu" });
            data.Add(new RefLanguage() { RefLanguageId = 410, Code = "sux", Description = "Sumerian" });
            data.Add(new RefLanguage() { RefLanguageId = 411, Code = "swa", Description = "Swahili" });
            data.Add(new RefLanguage() { RefLanguageId = 412, Code = "swe", Description = "Swedish" });
            data.Add(new RefLanguage() { RefLanguageId = 413, Code = "syc", Description = "Classical Syriac" });
            data.Add(new RefLanguage() { RefLanguageId = 414, Code = "syr", Description = "Syriac" });
            data.Add(new RefLanguage() { RefLanguageId = 415, Code = "tah", Description = "Tahitian" });
            data.Add(new RefLanguage() { RefLanguageId = 416, Code = "tai", Description = "Tai languages" });
            data.Add(new RefLanguage() { RefLanguageId = 417, Code = "tam", Description = "Tamil" });
            data.Add(new RefLanguage() { RefLanguageId = 418, Code = "tat", Description = "Tatar" });
            data.Add(new RefLanguage() { RefLanguageId = 419, Code = "tel", Description = "Telugu" });
            data.Add(new RefLanguage() { RefLanguageId = 420, Code = "tem", Description = "Timne" });
            data.Add(new RefLanguage() { RefLanguageId = 421, Code = "ter", Description = "Tereno" });
            data.Add(new RefLanguage() { RefLanguageId = 422, Code = "tet", Description = "Tetum" });
            data.Add(new RefLanguage() { RefLanguageId = 423, Code = "tgk", Description = "Tajik" });
            data.Add(new RefLanguage() { RefLanguageId = 424, Code = "tgl", Description = "Tagalog" });
            data.Add(new RefLanguage() { RefLanguageId = 425, Code = "tha", Description = "Thai" });
            data.Add(new RefLanguage() { RefLanguageId = 426, Code = "tib", Description = "Tibetan" });
            data.Add(new RefLanguage() { RefLanguageId = 427, Code = "tig", Description = "Tigre" });
            data.Add(new RefLanguage() { RefLanguageId = 428, Code = "tir", Description = "Tigrinya" });
            data.Add(new RefLanguage() { RefLanguageId = 429, Code = "tiv", Description = "Tiv" });
            data.Add(new RefLanguage() { RefLanguageId = 430, Code = "tkl", Description = "Tokelau" });
            data.Add(new RefLanguage() { RefLanguageId = 431, Code = "tlh", Description = "Klingon; tlhIngan-Hol" });
            data.Add(new RefLanguage() { RefLanguageId = 432, Code = "tli", Description = "Tlingit" });
            data.Add(new RefLanguage() { RefLanguageId = 433, Code = "tmh", Description = "Tamashek" });
            data.Add(new RefLanguage() { RefLanguageId = 434, Code = "tog", Description = "Tonga (Nyasa)" });
            data.Add(new RefLanguage() { RefLanguageId = 435, Code = "ton", Description = "Tonga (Tonga Islands)" });
            data.Add(new RefLanguage() { RefLanguageId = 436, Code = "tpi", Description = "Tok Pisin" });
            data.Add(new RefLanguage() { RefLanguageId = 437, Code = "tsi", Description = "Tsimshian" });
            data.Add(new RefLanguage() { RefLanguageId = 438, Code = "tsn", Description = "Tswana" });
            data.Add(new RefLanguage() { RefLanguageId = 439, Code = "tso", Description = "Tsonga" });
            data.Add(new RefLanguage() { RefLanguageId = 440, Code = "tuk", Description = "Turkmen" });
            data.Add(new RefLanguage() { RefLanguageId = 441, Code = "tum", Description = "Tumbuka" });
            data.Add(new RefLanguage() { RefLanguageId = 442, Code = "tup", Description = "Tupi languages" });
            data.Add(new RefLanguage() { RefLanguageId = 443, Code = "tur", Description = "Turkish" });
            data.Add(new RefLanguage() { RefLanguageId = 444, Code = "tut", Description = "Altaic languages" });
            data.Add(new RefLanguage() { RefLanguageId = 445, Code = "tvl", Description = "Tuvalu" });
            data.Add(new RefLanguage() { RefLanguageId = 446, Code = "twi", Description = "Twi" });
            data.Add(new RefLanguage() { RefLanguageId = 447, Code = "tyv", Description = "Tuvinian" });
            data.Add(new RefLanguage() { RefLanguageId = 448, Code = "udm", Description = "Udmurt" });
            data.Add(new RefLanguage() { RefLanguageId = 449, Code = "uga", Description = "Ugaritic" });
            data.Add(new RefLanguage() { RefLanguageId = 450, Code = "uig", Description = "Uighur; Uyghur" });
            data.Add(new RefLanguage() { RefLanguageId = 451, Code = "ukr", Description = "Ukrainian" });
            data.Add(new RefLanguage() { RefLanguageId = 452, Code = "umb", Description = "Umbundu" });
            data.Add(new RefLanguage() { RefLanguageId = 453, Code = "und", Description = "Undetermined" });
            data.Add(new RefLanguage() { RefLanguageId = 454, Code = "urd", Description = "Urdu" });
            data.Add(new RefLanguage() { RefLanguageId = 455, Code = "uzb", Description = "Uzbek" });
            data.Add(new RefLanguage() { RefLanguageId = 456, Code = "vai", Description = "Vai" });
            data.Add(new RefLanguage() { RefLanguageId = 457, Code = "ven", Description = "Venda" });
            data.Add(new RefLanguage() { RefLanguageId = 458, Code = "vie", Description = "Vietnamese" });
            data.Add(new RefLanguage() { RefLanguageId = 459, Code = "vol", Description = "Volap?k" });
            data.Add(new RefLanguage() { RefLanguageId = 460, Code = "vot", Description = "Votic" });
            data.Add(new RefLanguage() { RefLanguageId = 461, Code = "wak", Description = "Wakashan languages" });
            data.Add(new RefLanguage() { RefLanguageId = 462, Code = "wal", Description = "Wolaitta; Wolaytta" });
            data.Add(new RefLanguage() { RefLanguageId = 463, Code = "war", Description = "Waray" });
            data.Add(new RefLanguage() { RefLanguageId = 464, Code = "was", Description = "Washo" });
            data.Add(new RefLanguage() { RefLanguageId = 465, Code = "wel", Description = "Welsh" });
            data.Add(new RefLanguage() { RefLanguageId = 466, Code = "wen", Description = "Sorbian languages" });
            data.Add(new RefLanguage() { RefLanguageId = 467, Code = "wln", Description = "Walloon" });
            data.Add(new RefLanguage() { RefLanguageId = 468, Code = "wol", Description = "Wolof" });
            data.Add(new RefLanguage() { RefLanguageId = 469, Code = "xal", Description = "Kalmyk; Oirat" });
            data.Add(new RefLanguage() { RefLanguageId = 470, Code = "xho", Description = "Xhosa" });
            data.Add(new RefLanguage() { RefLanguageId = 471, Code = "yao", Description = "Yao" });
            data.Add(new RefLanguage() { RefLanguageId = 472, Code = "yap", Description = "Yapese" });
            data.Add(new RefLanguage() { RefLanguageId = 473, Code = "yid", Description = "Yiddish" });
            data.Add(new RefLanguage() { RefLanguageId = 474, Code = "yor", Description = "Yoruba" });
            data.Add(new RefLanguage() { RefLanguageId = 475, Code = "ypk", Description = "Yupik languages" });
            data.Add(new RefLanguage() { RefLanguageId = 476, Code = "zap", Description = "Zapotec" });
            data.Add(new RefLanguage() { RefLanguageId = 477, Code = "zbl", Description = "Blissymbols; Blissymbolics; Bliss" });
            data.Add(new RefLanguage() { RefLanguageId = 478, Code = "zen", Description = "Zenaga" });
            data.Add(new RefLanguage() { RefLanguageId = 479, Code = "zgh", Description = "Standard Moroccan Tamazight" });
            data.Add(new RefLanguage() { RefLanguageId = 480, Code = "zha", Description = "Zhuang; Chuang" });
            data.Add(new RefLanguage() { RefLanguageId = 481, Code = "znd", Description = "Zande languages" });
            data.Add(new RefLanguage() { RefLanguageId = 482, Code = "zul", Description = "Zulu" });
            data.Add(new RefLanguage() { RefLanguageId = 483, Code = "zun", Description = "Zuni" });
            data.Add(new RefLanguage() { RefLanguageId = 484, Code = "zxx", Description = "No linguistic content; Not applicable" });
            data.Add(new RefLanguage() { RefLanguageId = 485, Code = "zza", Description = "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" });

            return data;
        }
    }
}
