IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Staging' AND TABLE_NAME = 'StagingValidationRules_ReportsXREF') BEGIN
	DROP TABLE [Staging].[StagingValidationRules_ReportsXREF]
END
