IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'Rollover_Previous_Year_Metadata') BEGIN
	DROP PROCEDURE [App].[Rollover_Previous_Year_Metadata]
END