IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'Wrapper_Migrate_Membership_to_IDS') 
BEGIN
	DROP PROCEDURE [Staging].[Wrapper_Migrate_Membership_to_IDS]
END


