
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Utilities' AND ROUTINE_NAME = 'Cleanup_Grades_Offered') 
BEGIN
	DROP PROCEDURE [Utilities].[Cleanup_Grades_Offered]
END








