IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'Staging-to-DimPeople_K12Students') BEGIN
	DROP PROCEDURE [Staging].[Staging-to-DimPeople_K12Students]
END