
DELETE CO 
FROM APP.CATEGORYSETS CS
JOIN APP.CATEGORYOPTIONS CO
	ON CS.CATEGORYSETID = CO.CATEGORYSETID
LEFT JOIN APP.CATEGORYSETS CS2
	ON CS.GENERATEREPORTID = CS2.GENERATEREPORTID
	AND CS.ORGANIZATIONLEVELID = CS2.ORGANIZATIONLEVELID
	AND CS.SUBMISSIONYEAR = CS2.SUBMISSIONYEAR
	AND CS2.CATEGORYSETCODE = 'TOT'
WHERE CS.CATEGORYSETCODE = 'EUT'
	AND CS2.CATEGORYSETID IS NOT NULL

DELETE CS 
FROM APP.CATEGORYSETS CS
LEFT JOIN APP.CATEGORYSETS CS2
	ON CS.GENERATEREPORTID = CS2.GENERATEREPORTID
	AND CS.ORGANIZATIONLEVELID = CS2.ORGANIZATIONLEVELID
	AND CS.SUBMISSIONYEAR = CS2.SUBMISSIONYEAR
	AND CS2.CATEGORYSETCODE = 'TOT'
WHERE CS.CATEGORYSETCODE = 'EUT'
	AND CS2.CATEGORYSETID IS NOT NULL

UPDATE APP.CATEGORYSETS
SET CATEGORYSETCODE = 'TOT', CATEGORYSETNAME = 'TOTAL OF THE EDUCATION UNIT'
WHERE CATEGORYSETCODE = 'EUT'