using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace generate.core.Dtos.App
{
    public class DataSetYearVersionDetailsByAllAbbrv
    {
        public string AggregationLongName { get; set; }
        public string AggregationShortName { get; set; }
        public string CategoryAbbr { get; set; }
        public string CategoryComments { get; set; }
        public string CategoryDefinition { get; set; }
        public string CategoryName { get; set; }
        public int? CategoryOrderNum { get; set; }
        public string CategoryVersionNum { get; set; }
        public string CollectionAbbrv { get; set; }
        public string CollectionDesc { get; set; }
        public int? CollectionID { get; set; }
        public string CollectionName { get; set; }
        public string CSA { get; set; }
        public string CSB { get; set; }
        public string CSC { get; set; }
        public string CSD { get; set; }
        public string CSE { get; set; }
        public string CSF { get; set; }
        public string CSG { get; set; }
        public string CSH { get; set; }
        public string CSI { get; set; }
        public string CSJ { get; set; }
        public string CSK { get; set; }
        public string DataArea { get; set; }
        public string DEAbbr { get; set; }
        public string DEComment { get; set; }
        public string DEDataTypeAbbr { get; set; }
        public string DEDataTypeDesc { get; set; }
        public int? DEDataTypeID { get; set; }
        public string DEDataTypeName { get; set; }
        public string DEMask { get; set; }
        public string DEName { get; set; }
        public int? DEOrderNum { get; set; }
        public int? DERequiredFlag { get; set; }
        public string DETypeAbbr { get; set; }
        public string DETypeDesc { get; set; }
        public int? DETypeID { get; set; }
        public string DETypeName { get; set; }
        public string DGApprovalDt { get; set; }
        public DateTime? DGApprovalDtStr { get; set; }
        public string DGComment { get; set; }
        public string DGDefinition { get; set; }
        public string DGDuplicationComment { get; set; }
        public int? DGEDID { get; set; }
        public string DGFactTypeAbbr { get; set; }
        public string DGFactTypeDesc { get; set; }
        public int? DGFactTypeID { get; set; }
        public string DGFactTypeName { get; set; }
        public string DGName { get; set; }
        public string DGScopeComment { get; set; }
        public string DSAbbrv { get; set; }
        public int? DSID { get; set; }
        public string DSName { get; set; }
        public string ElectronicFileDesc { get; set; }
        public int? EqualToTotalFlag { get; set; }
        public string FileDueDt { get; set; }
        public string FileDueDtNote { get; set; }
        public string FileDueDtStr { get; set; }
        public string FileSpecApproverDt { get; set; }
        public string FileSpecApproverDtStr { get; set; }
        public string FileSpecComment { get; set; }
        public string FileSpecName { get; set; }
        public string FileSpecNewFlag { get; set; }
        public string FileSpecNum { get; set; }
        public string FileSpecPlanningNote { get; set; }
        public int? FileSpecVersionID { get; set; }
        public string FileType { get; set; }
        public int? HasAllStudents { get; set; }
        public int? HasCS { get; set; }
        public int? HasEUT { get; set; }
        public int? HasST { get; set; }
        public int? IsAggCat { get; set; }
        public int? IsDatacollEnabledLEA { get; set; }
        public int? IsDatacollEnabledSCH { get; set; }
        public int? IsDatacollEnabledSEA { get; set; }
        public int? IsDatacollEnabledSTE { get; set; }
        public int? IsNonAggregation { get; set; }
        public int? IsRestrictedUse { get; set; }
        public string Justification { get; set; }
        public int? LEALevelFlag { get; set; }
        public string PVAbbr { get; set; }
        public string PVBusinessAbbr { get; set; }
        public string PVComment { get; set; }
        public string PVDescription { get; set; }
        public int? PVDisplayorder { get; set; }
        public string PVName { get; set; }
        public string PVTypeAbbr { get; set; }
        public string PVTypeDesc { get; set; }
        public int? PVTypeID { get; set; }
        public string PVTypeName { get; set; }
        public int? PVVersionNum { get; set; }
        public int? ReleaseID { get; set; }
        public string ReleaseNum { get; set; }
        public string RestrictedUseScope { get; set; }
        public int? RowID { get; set; }
        public string RptPrdDesc { get; set; }
        public string RptPrdName { get; set; }
        public int? SCHLevelFlag { get; set; }
        public int? SEALevelFlag { get; set; }
        public string SpecialHandling { get; set; }
        public string ST01 { get; set; }
        public string ST02 { get; set; }
        public string ST03 { get; set; }
        public string ST04 { get; set; }
        public string ST05 { get; set; }
        public string ST06 { get; set; }
        public string ST07 { get; set; }
        public string ST08 { get; set; }
        public string ST09 { get; set; }
        public string ST10 { get; set; }
        public string StewardAbbr { get; set; }
        public string StewardDisplayOrder { get; set; }
        public string StewardName { get; set; }
        public string TableName { get; set; }
        public int? VersionID { get; set; }
        public int? VersionNum { get; set; }
        public string VersionStatusAbbrv { get; set; }
        public string VersionStatusDesc { get; set; }
        public int? VersionStatusID { get; set; }
        public string WebSessionID { get; set; }
        public string YearAbbrv { get; set; }
        public int? YearID { get; set; }
        public string YearName { get; set; }
        public string YearTypeAbbrv { get; set; }
        public int? YearTypeID { get; set; }
        public string YearTypeName { get; set; }
        public int? YearValue { get; set; }
    }
}
