IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetRefOrganizationLocationTypeId') BEGIN
	DROP FUNCTION [App].[GetRefOrganizationLocationTypeId]
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'GetRefOrganizationLocationTypeId') BEGIN
	DROP FUNCTION [Staging].[GetRefOrganizationLocationTypeId]
END