IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetOrganizationIdentifierTypeId') BEGIN
	DROP FUNCTION [App].[GetOrganizationIdentifierTypeId]
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'GetOrganizationIdentifierTypeId') BEGIN
	DROP FUNCTION [Staging].[GetOrganizationIdentifierTypeId]
END