IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'APP' AND ROUTINE_NAME = 'GetRefInstitutionTelephoneType') BEGIN
	DROP FUNCTION [App].[GetRefInstitutionTelephoneType]
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Staging' AND ROUTINE_NAME = 'GetRefInstitutionTelephoneType') BEGIN
	DROP FUNCTION [Staging].[GetRefInstitutionTelephoneType]
END