
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'Utilities' AND ROUTINE_NAME = 'Cleanup_Debug_Tables') 
BEGIN
	DROP PROCEDURE [Utilities].[Cleanup_Debug_Tables]
END








